{
  "swagger": "2.0",
  "info": {
    "title": "apaleo Identity API - not safe for work",
    "version": "v0-nsfw"
  },
  "host": "identity.apaleo.com",
  "paths": {
    "/api/v0-nsfw/configuration/api-resources": {
      "get": {
        "tags": [
          "ApiResources"
        ],
        "summary": "Returns a list of API resources.",
        "description": "Returns all API endpoints and the scopes needed to access them.<br>You need to be authorized (no particular scope required)",
        "operationId": "ApiConfigurationApi-resourcesGet",
        "security": [
          {
            "oauth2": [
              
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/configuration/connect-clients": {
      "get": {
        "tags": [
          "ConnectClients"
        ],
        "summary": "Returns a list of connect clients.",
        "description": "Returns a list of all connect clients.<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationConnect-clientsGet",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ConnectClients"
        ],
        "summary": "Creates a connect client.",
        "description": "Creates a new connect client based on provided model.<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationConnect-clientsPost",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/configuration/connect-clients/{clientId}": {
      "get": {
        "tags": [
          "ConnectClients"
        ],
        "summary": "Returns a connect client.",
        "description": "Returns a connect client for a specific client ID.<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationConnect-clientsByClientIdGet",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "ConnectClients"
        ],
        "summary": "Modify a connect client.",
        "description": "Allows to modify a connect client.\r\nAllowed for modification:\r\n- Replace clientName\r\n- Replace logoUri\r\n- Add, replace and remove redirectUris\r\n- Add, replace and remove allowedScopes\r\n- Add, replace and remove properties<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationConnect-clientsByClientIdPatch",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ConnectClients"
        ],
        "summary": "Deletes a connect client.",
        "description": "Deletes a connect client.<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationConnect-clientsByClientIdDelete",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/configuration/connect-clients/{clientId}/connected-accounts/{accountCode}": {
      "delete": {
        "tags": [
          "ConnectClients"
        ],
        "summary": "Disconnects an account from a client",
        "description": "Disconnects the provided account from the client<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationConnect-clientsByClientIdConnected-accountsByAccountCodeDelete",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/configuration/connect-clients/{clientId}/secrets": {
      "get": {
        "tags": [
          "ConnectClients"
        ],
        "summary": "Returns a list of secrets of a client.",
        "description": "Returns a list of all secrets of a client. Each secret contains an ID and description. Not used secrets can be deleted by ID.<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationConnect-clientsByClientIdSecretsGet",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ConnectClients"
        ],
        "summary": "Adds a new auto generated secret to secrets collection.",
        "description": "Returned secret is not stored anywhere. Please remember it, otherwise create a new one and remove not used secrets.<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationConnect-clientsByClientIdSecretsPost",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/configuration/connect-clients/{clientId}/secrets/{secretId}": {
      "delete": {
        "tags": [
          "ConnectClients"
        ],
        "summary": "Deletes a secret from a client.",
        "description": "Secret ID is a part of a model returned by secrets GET endpoint.<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationConnect-clientsByClientIdSecretsBySecretIdDelete",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/configuration/connected-apps": {
      "get": {
        "tags": [
          "ConnectedApps"
        ],
        "description": "<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationConnected-appsGet",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/configuration/connected-apps/{clientId}": {
      "delete": {
        "tags": [
          "ConnectedApps"
        ],
        "description": "<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationConnected-appsByClientIdDelete",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/configuration/credentials-clients": {
      "get": {
        "tags": [
          "CredentialsClients"
        ],
        "summary": "Returns a list of credentials clients.",
        "description": "Returns a list of all credentials clients.<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationCredentials-clientsGet",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "CredentialsClients"
        ],
        "summary": "Creates a credentials client.",
        "description": "Creates a new credentials client based on provided model.<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationCredentials-clientsPost",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/configuration/credentials-clients/{clientId}": {
      "get": {
        "tags": [
          "CredentialsClients"
        ],
        "summary": "Returns a credentials client.",
        "description": "Returns a credentials client for a specific client ID.<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationCredentials-clientsByClientIdGet",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "CredentialsClients"
        ],
        "summary": "Modify a credentials client.",
        "description": "Allows to modify a credentials client of the current account.\r\nAllowed for modification:\r\n- Replace clientName\r\n- Add, replace and remove allowedScopes\r\n- Add, replace and remove properties<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationCredentials-clientsByClientIdPatch",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "CredentialsClients"
        ],
        "summary": "Deletes a credentials client.",
        "description": "Deletes a credentials client.<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationCredentials-clientsByClientIdDelete",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/configuration/credentials-clients/{clientId}/secrets": {
      "get": {
        "tags": [
          "CredentialsClients"
        ],
        "summary": "Returns a list of secrets of a client.",
        "description": "Returns a list of all secrets of a client. Each secret contains an ID and description. Not used secrets can be deleted by ID.<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationCredentials-clientsByClientIdSecretsGet",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "CredentialsClients"
        ],
        "summary": "Adds a new auto generated secret to secrets collection.",
        "description": "Returned secret is not stored anywhere. Please remember it, otherwise create a new one and remove not used secrets.<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationCredentials-clientsByClientIdSecretsPost",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/configuration/credentials-clients/{clientId}/secrets/{secretId}": {
      "delete": {
        "tags": [
          "CredentialsClients"
        ],
        "summary": "Deletes a secret from a client.",
        "description": "Secret ID is a part of a model returned by secrets GET endpoint.<br>You must have this scope: 'identity:clients.manage'.",
        "operationId": "ApiConfigurationCredentials-clientsByClientIdSecretsBySecretIdDelete",
        "security": [
          {
            "oauth2": [
              "identity:clients.manage"
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/account/invitations": {
      "get": {
        "tags": [
          "Invitation"
        ],
        "summary": "Returns a list of invitations for the current account",
        "description": "Returns a list of all invitations to the current account.<br>You must have at least one of these scopes: 'identity:account-users.manage, identity:account-users.read'.",
        "operationId": "ApiAccountInvitationsGet",
        "security": [
          {
            "oauth2": [
              "identity:account-users.manage",
              "identity:account-users.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Invitation"
        ],
        "summary": "Invites a user to the current account",
        "description": "Invites a person to the current account with the requested roles and properties.<br />\r\nWhen you specify 'IsAccountAdmin', the user will automatically have access to all properties in all roles.<br />\r\nThe <i>user</i> will only be created or linked to the account, when the person accepts the invitation.<br>You must have this scope: 'identity:account-users.manage'.",
        "operationId": "ApiAccountInvitationsPost",
        "security": [
          {
            "oauth2": [
              "identity:account-users.manage"
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/account/invitations/{email}": {
      "delete": {
        "tags": [
          "Invitation"
        ],
        "summary": "Deletes an invitation for the current account if it exists",
        "description": "<br>You must have this scope: 'identity:account-users.manage'.",
        "operationId": "ApiAccountInvitationsByEmailDelete",
        "security": [
          {
            "oauth2": [
              "identity:account-users.manage"
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/roles": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "Returns a static list of all roles.",
        "description": "",
        "operationId": "ApiRolesGet"
      }
    },
    "/api/v0-nsfw/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Returns a list of users for the current account.",
        "description": "Returns a list of all users that have access to the current account.<br>You must have at least one of these scopes: 'identity:account-users.manage, identity:account-users.read'.",
        "operationId": "ApiUsersGet",
        "security": [
          {
            "oauth2": [
              "identity:account-users.manage",
              "identity:account-users.read"
            ]
          }
        ]
      }
    },
    "/api/v0-nsfw/users/{userId}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Returns a user for the current account.",
        "description": "Returns a user in the current account for a specific subjectId address.<br>You must have at least one of these scopes: 'identity:account-users.manage, identity:account-users.read'.",
        "operationId": "ApiUsersByUserIdGet",
        "security": [
          {
            "oauth2": [
              "identity:account-users.manage",
              "identity:account-users.read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Users"
        ],
        "summary": "Modify user in an account.",
        "description": "Modify user in an account.\r\nAllowed operations:\r\n- Replace firstName and lastName\r\n- Replace isAccountAdmin (setting it to true or false)\r\n- Replace enabled (setting it to true or false)\r\n- Replace properties<br>You must have this scope: 'identity:account-users.manage'.",
        "operationId": "ApiUsersByUserIdPatch",
        "security": [
          {
            "oauth2": [
              "identity:account-users.manage"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "oauth2": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "https://identity.apaleo.com/connect/authorize",
      "scopes": {
        "identity:account-users.manage": "Manage account users",
        "identity:clients.manage": "Manage clients"
      }
    }
  }
}
