{
    "swagger": "2.0",
    "info": {
      "title": "apaleo Inventory API",
      "description": "",
      "version": "v1"
    },
    "host": "api.apaleo.com",
    "paths": {
      "/inventory/v1/properties": {
        "get": {
          "tags": [
            "Property"
          ],
          "summary": "Get a properties list",
          "description": "Get the list of properties.<br>You need to be authorized (no particular scope required)",
          "operationId": "InventoryPropertiesGet",
          "security": [
            {
              "oauth2": [
                
              ]
            }
          ]
        },
        "post": {
          "tags": [
            "Property"
          ],
          "summary": "Creates a property",
          "description": "Use this call to create a new property.<br>You must have at least one of these scopes: 'properties.create, setup.manage'.",
          "operationId": "InventoryPropertiesPost",
          "security": [
            {
              "oauth2": [
                "properties.create",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/inventory/v1/properties/$count": {
        "get": {
          "tags": [
            "Property"
          ],
          "summary": "Return total count of properties",
          "description": "Return total count of properties<br>You need to be authorized (no particular scope required)",
          "operationId": "InventoryProperties$countGet",
          "security": [
            {
              "oauth2": [
                
              ]
            }
          ]
        }
      },
      "/inventory/v1/properties/{id}": {
        "head": {
          "tags": [
            "Property"
          ],
          "summary": "Check if a property exists",
          "description": "Check if a property exists by id.<br>You need to be authorized (no particular scope required)",
          "operationId": "InventoryPropertiesByIdHead",
          "security": [
            {
              "oauth2": [
                
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "Property"
          ],
          "summary": "Get a property",
          "description": "Get a property by id.<br>You need to be authorized (no particular scope required)",
          "operationId": "InventoryPropertiesByIdGet",
          "security": [
            {
              "oauth2": [
                
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "Property"
          ],
          "summary": "Allows to modify property",
          "description": "Here's a list of allowed operations:\r\n- Replace Name\r\n- Add, replace and remove Description\r\n- Replace CompanyName\r\n- Add, replace and remove ManagingDirectors\r\n- Replace CommercialRegisterEntry\r\n- Replace TaxId\r\n- Replace Location\r\n- Add, replace and remove BankAccount\r\n- Replace PaymentTerms\r\n- Set IsTemplate<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.",
          "operationId": "InventoryPropertiesByIdPatch",
          "security": [
            {
              "oauth2": [
                "properties.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/inventory/v1/types/countries": {
        "get": {
          "tags": [
            "Types"
          ],
          "summary": "Returns a list of supported countries.",
          "description": "Returns a list of ISO country codes that could be used to create properties.<br>You need to be authorized (no particular scope required)",
          "operationId": "InventoryTypesCountriesGet",
          "security": [
            {
              "oauth2": [
                
              ]
            }
          ]
        }
      },
      "/inventory/v1/units/{id}": {
        "patch": {
          "tags": [
            "Unit"
          ],
          "summary": "Allows to patch unit",
          "description": "Here's a list of allowed operations:\r\n- Set unit condition\r\n- Set unit description\r\n- Set unit name\r\n- Set unit unitGroupId\r\n- Set unit maxPersons\r\n- Add unit attribute\r\n- Remove unit attribute<br>You must have at least one of these scopes: 'units.manage, setup.manage'.",
          "operationId": "InventoryUnitsByIdPatch",
          "security": [
            {
              "oauth2": [
                "units.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "Unit"
          ],
          "summary": "Get a unit",
          "description": "Get a unit by id.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'.",
          "operationId": "InventoryUnitsByIdGet",
          "security": [
            {
              "oauth2": [
                "units.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "head": {
          "tags": [
            "Unit"
          ],
          "summary": "Check if a unit exists",
          "description": "Check if a unit exists by id.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'.",
          "operationId": "InventoryUnitsByIdHead",
          "security": [
            {
              "oauth2": [
                "units.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "Unit"
          ],
          "summary": "Delete a unit",
          "description": "Use this call to delete a unit.<br>You must have at least one of these scopes: 'units.delete, setup.manage'.",
          "operationId": "InventoryUnitsByIdDelete",
          "security": [
            {
              "oauth2": [
                "units.delete",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/inventory/v1/units": {
        "patch": {
          "tags": [
            "Unit"
          ],
          "summary": "Allows to patch one or more units",
          "description": "Here's a list of allowed operations:\r\n- Set unit condition\r\n- Set unit description\r\n- Set unit name\r\n- Set unit unitGroupId\r\n- Set unit maxPersons\r\n- Add unit attribute\r\n- Remove unit attribute<br>You must have at least one of these scopes: 'units.manage, setup.manage'.",
          "operationId": "InventoryUnitsPatch",
          "security": [
            {
              "oauth2": [
                "units.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "Unit"
          ],
          "summary": "Get a units list",
          "description": "Get the list of units.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'.",
          "operationId": "InventoryUnitsGet",
          "security": [
            {
              "oauth2": [
                "units.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "post": {
          "tags": [
            "Unit"
          ],
          "summary": "Create a unit",
          "description": "Use this call to create a new unit.<br>You must have at least one of these scopes: 'units.create, setup.manage'.",
          "operationId": "InventoryUnitsPost",
          "security": [
            {
              "oauth2": [
                "units.create",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/inventory/v1/units/$count": {
        "get": {
          "tags": [
            "Unit"
          ],
          "summary": "Returns number of units",
          "description": "Returns number of units matching the filter criteria<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'.",
          "operationId": "InventoryUnits$countGet",
          "security": [
            {
              "oauth2": [
                "units.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/inventory/v1/units/bulk": {
        "post": {
          "tags": [
            "Unit"
          ],
          "summary": "Create multiple units",
          "description": "Use this call to create multiple units, following a naming rule.<br>You must have at least one of these scopes: 'units.create, setup.manage'.",
          "operationId": "InventoryUnitsBulkPost",
          "security": [
            {
              "oauth2": [
                "units.create",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/inventory/v1/unit-attributes/{id}": {
        "get": {
          "tags": [
            "UnitAttribute"
          ],
          "summary": "Get unit attribute by id",
          "description": "Get unit attribute by id<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'.",
          "operationId": "InventoryUnit-attributesByIdGet",
          "security": [
            {
              "oauth2": [
                "unitattributes.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "UnitAttribute"
          ],
          "summary": "Allows to modify unit attribute",
          "description": "Here's a list of allowed operations:\r\n- Replace / Remove Description<br>You must have at least one of these scopes: 'unitattributes.manage, setup.manage'.",
          "operationId": "InventoryUnit-attributesByIdPatch",
          "security": [
            {
              "oauth2": [
                "unitattributes.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "UnitAttribute"
          ],
          "summary": "Deletes unit attribute",
          "description": "Deletes unit attribute<br>You must have at least one of these scopes: 'unitattributes.delete, setup.manage'.",
          "operationId": "InventoryUnit-attributesByIdDelete",
          "security": [
            {
              "oauth2": [
                "unitattributes.delete",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "head": {
          "tags": [
            "UnitAttribute"
          ],
          "summary": "Check if a unit attribute exists",
          "description": "Check if a unit attribute exists<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'.",
          "operationId": "InventoryUnit-attributesByIdHead",
          "security": [
            {
              "oauth2": [
                "unitattributes.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/inventory/v1/unit-attributes": {
        "get": {
          "tags": [
            "UnitAttribute"
          ],
          "summary": "Get unit attribute list",
          "description": "Get unit attribute list<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'.",
          "operationId": "InventoryUnit-attributesGet",
          "security": [
            {
              "oauth2": [
                "unitattributes.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "post": {
          "tags": [
            "UnitAttribute"
          ],
          "summary": "Create a unit attribute",
          "description": "Use this call to create a new unit attribute.<br>You must have at least one of these scopes: 'unitattributes.create, setup.manage'.",
          "operationId": "InventoryUnit-attributesPost",
          "security": [
            {
              "oauth2": [
                "unitattributes.create",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/inventory/v1/unit-groups": {
        "post": {
          "tags": [
            "UnitGroup"
          ],
          "summary": "Create a unit group",
          "description": "Use this call to create a new unit group.<br>You must have at least one of these scopes: 'unitgroups.create, setup.manage'.",
          "operationId": "InventoryUnit-groupsPost",
          "security": [
            {
              "oauth2": [
                "unitgroups.create",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "UnitGroup"
          ],
          "summary": "Get all unit groups, or all unit groups for a property",
          "description": "Get the list of unit groups.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'.",
          "operationId": "InventoryUnit-groupsGet",
          "security": [
            {
              "oauth2": [
                "unitgroups.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/inventory/v1/unit-groups/$count": {
        "get": {
          "tags": [
            "UnitGroup"
          ],
          "summary": "Returns number of unit groups",
          "description": "Returns number of unit groups matching the filter criteria<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'.",
          "operationId": "InventoryUnit-groups$countGet",
          "security": [
            {
              "oauth2": [
                "unitgroups.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/inventory/v1/unit-groups/{id}": {
        "head": {
          "tags": [
            "UnitGroup"
          ],
          "summary": "Check if a unit group exists",
          "description": "Check if a unit group exists by id.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'.",
          "operationId": "InventoryUnit-groupsByIdHead",
          "security": [
            {
              "oauth2": [
                "unitgroups.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "UnitGroup"
          ],
          "summary": "Get a unit group",
          "description": "Get a unit group by id.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'.",
          "operationId": "InventoryUnit-groupsByIdGet",
          "security": [
            {
              "oauth2": [
                "unitgroups.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "put": {
          "tags": [
            "UnitGroup"
          ],
          "summary": "Replace a unit group",
          "description": "Use this call to modify a unit group.<br>You must have at least one of these scopes: 'unitgroups.manage, setup.manage'.",
          "operationId": "InventoryUnit-groupsByIdPut",
          "security": [
            {
              "oauth2": [
                "unitgroups.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "UnitGroup"
          ],
          "summary": "Delete a unit group",
          "description": "Use this call to delete a unit group.<br>You must have at least one of these scopes: 'unitgroups.delete, setup.manage'.",
          "operationId": "InventoryUnit-groupsByIdDelete",
          "security": [
            {
              "oauth2": [
                "unitgroups.delete",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/settings/v1/age-categories/{id}": {
        "get": {
          "tags": [
            "AgeCategory"
          ],
          "summary": "Get an age category",
          "description": "Get an age category by id.<br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "SettingsAge-categoriesByIdGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "AgeCategory"
          ],
          "summary": "Allows to modify properties of an age category",
          "description": "Here is the list of operations that are currently allowed:\r\n- Replace name, minimum age and maximum age<br /><br /><br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "SettingsAge-categoriesByIdPatch",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "AgeCategory"
          ],
          "summary": "Delete an age category",
          "description": "Use this call to delete an age category. You can only delete an age category if it is not already used in a rate\r\nplan to define age specific prices.<br /><br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "SettingsAge-categoriesByIdDelete",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/settings/v1/age-categories": {
        "post": {
          "tags": [
            "AgeCategory"
          ],
          "summary": "Create an age category",
          "description": "Use this call to create a new age category. The age ranges for categories must not overlap each other and the\r\nallowed values span from 0 to 17.<br /><br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "SettingsAge-categoriesPost",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "AgeCategory"
          ],
          "summary": "Get an age category list",
          "description": "Get the list of age categories.<br /><br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "SettingsAge-categoriesGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/cancellation-policies": {
        "post": {
          "tags": [
            "CancellationPolicy"
          ],
          "summary": "Create a cancellation policy.",
          "description": "Create a cancellation policy.<br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "RateplanCancellation-policiesPost",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "CancellationPolicy"
          ],
          "summary": "Get all cancellation policies.",
          "description": "Get the list of cancellation policies.<br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "RateplanCancellation-policiesGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/cancellation-policies/{id}": {
        "get": {
          "tags": [
            "CancellationPolicy"
          ],
          "summary": "Get a specific cancellation policy.",
          "description": "Get a specific cancellation policy.<br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "RateplanCancellation-policiesByIdGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "CancellationPolicy"
          ],
          "summary": "Allows to modify properties of a cancellation policy",
          "description": "Here is the list of operations that are currently allowed:\r\n- Replace name and description\r\n- Replace the period from reference\r\n- Replace the reference\r\n- Replace the fee details: fixed and percent values<br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "RateplanCancellation-policiesByIdPatch",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "CancellationPolicy"
          ],
          "summary": "Delete a cancellation policy",
          "description": "Use this call to delete a cancellation policy.<br>You must have this scope: 'setup.manage'.",
          "operationId": "RateplanCancellation-policiesByIdDelete",
          "security": [
            {
              "oauth2": [
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/companies": {
        "post": {
          "tags": [
            "Company"
          ],
          "summary": "Create a company",
          "description": "Use this call to create a new company.<br>You must have at least one of these scopes: 'companies.create, companies.manage'.",
          "operationId": "RateplanCompaniesPost",
          "security": [
            {
              "oauth2": [
                "companies.create",
                "companies.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "Company"
          ],
          "summary": "Get a list of companies",
          "description": "Get the list of companies.<br /><br>You must have at least one of these scopes: 'companies.read, companies.manage'.",
          "operationId": "RateplanCompaniesGet",
          "security": [
            {
              "oauth2": [
                "companies.read",
                "companies.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/companies/{id}": {
        "get": {
          "tags": [
            "Company"
          ],
          "summary": "Get a company",
          "description": "Get a company by ID.<br>You must have at least one of these scopes: 'companies.read, companies.manage'.",
          "operationId": "RateplanCompaniesByIdGet",
          "security": [
            {
              "oauth2": [
                "companies.read",
                "companies.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "Company"
          ],
          "summary": "Modify a company",
          "description": "Here is the list of operations that are currently allowed:\r\n- Replace name, address, tax ID\r\n- Add and remove rate plans<br>You must have this scope: 'companies.manage'.",
          "operationId": "RateplanCompaniesByIdPatch",
          "security": [
            {
              "oauth2": [
                "companies.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "Company"
          ],
          "summary": "Delete a company",
          "description": "Deletes a company.\r\nWarning: This operation also removes company from all rate plans if not yet used.\r\nThe deleted company won't be available in the company VAT report anymore.<br>You must have this scope: 'companies.manage'.",
          "operationId": "RateplanCompaniesByIdDelete",
          "security": [
            {
              "oauth2": [
                "companies.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/corporate-codes/codes": {
        "get": {
          "tags": [
            "CorporateCodes"
          ],
          "summary": "Returns a list of corporate codes.",
          "description": "Returns all existing corporate codes that match given criteria.<br>You must have this scope: 'rateplans.read-corporate'.",
          "operationId": "RateplanCorporate-codesCodesGet",
          "security": [
            {
              "oauth2": [
                "rateplans.read-corporate",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/no-show-policies": {
        "post": {
          "tags": [
            "NoShowPolicy"
          ],
          "summary": "Create a no-show policy.",
          "description": "Create a no-show policy.<br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "RateplanNo-show-policiesPost",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "NoShowPolicy"
          ],
          "summary": "Get all no-show policies.",
          "description": "Get the list of no-show policies.<br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "RateplanNo-show-policiesGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/no-show-policies/{id}": {
        "get": {
          "tags": [
            "NoShowPolicy"
          ],
          "summary": "Get a specific no-show policy.",
          "description": "Get a specific no-show policy.<br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "RateplanNo-show-policiesByIdGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "NoShowPolicy"
          ],
          "summary": "Allows to modify properties of a no-show policy",
          "description": "Here is the list of operations that are currently allowed:\r\n- Replace name and description\r\n- Replace the fee details: fixed and percent values<br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "RateplanNo-show-policiesByIdPatch",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "NoShowPolicy"
          ],
          "summary": "Delete a no-show policy",
          "description": "Use this call to delete a no-show policy.<br>You must have this scope: 'setup.manage'.",
          "operationId": "RateplanNo-show-policiesByIdDelete",
          "security": [
            {
              "oauth2": [
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/promo-codes/codes": {
        "get": {
          "tags": [
            "PromoCodes"
          ],
          "summary": "Returns a list of promo codes.",
          "description": "Returns all existing promo codes that match given criteria.<br>You must have this scope: 'rateplans.read-corporate'.",
          "operationId": "RateplanPromo-codesCodesGet",
          "security": [
            {
              "oauth2": [
                "rateplans.read-corporate",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/rate-plans/{id}/rates": {
        "get": {
          "tags": [
            "Rate"
          ],
          "summary": "Returns a list of rates.",
          "description": "Returns all rates for a specific rate plan within the specified time range. If a rate has not\r\nbeen initialized, it will still be returned, but anything besides the from and to values will be empty.\r\nThe time range of a rate is defined by the time slice definition of the rate plan.<br />\r\nTime ranges with no initialized rates will not be available for sell.<br /><br />\r\nTo be able to read rates for a corporate rate plan a client must additionally have\r\nthe 'ra[...]",
          "operationId": "RateplanRate-plansByIdRatesGet",
          "security": [
            {
              "oauth2": [
                "rates.read",
                "rates.manage",
                "admin"
              ]
            }
          ]
        },
        "put": {
          "tags": [
            "Rate"
          ],
          "summary": "Initializes and changes the rates for the rate plan.",
          "description": "All rates specified in the request will be initialized, or overwritten if they already exist.\r\n<br /><br />\r\nMake sure that the from and to date and time in the rates match the time slice definition of the rate plan.\r\nThe easiest way to achieve this is calling the GET /rate-plans/{id}/rates for the time range you want to update\r\nand then resend the payload with the set prices and restrictions.<br>You must have this scope: 'rates.manage'.",
          "operationId": "RateplanRate-plansByIdRatesPut",
          "security": [
            {
              "oauth2": [
                "rates.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "Rate"
          ],
          "summary": "Deletes the rates for the rate plan",
          "description": "Deletes all rates in the specifed time range.<br>You must have at least one of these scopes: 'rates.delete, rates.manage'.",
          "operationId": "RateplanRate-plansByIdRatesDelete",
          "security": [
            {
              "oauth2": [
                "rates.delete",
                "rates.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/rate-plans/{id}/rates/$count": {
        "get": {
          "tags": [
            "Rate"
          ],
          "summary": "Returns the number of rates for a specific rate plan within the specifed time range.",
          "description": "To be able to count rates for a corporate rate plan a client must additionaly have\r\nthe 'rateplans.read-corporate' scope.<br>You must have at least one of these scopes: 'rates.read, rates.manage'.",
          "operationId": "RateplanRate-plansByIdRates$countGet",
          "security": [
            {
              "oauth2": [
                "rates.read",
                "rates.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/rates": {
        "patch": {
          "tags": [
            "Rate"
          ],
          "summary": "Allows to patch the rates of multiple rate plans.",
          "description": "Note that the specified PATCH operations are applied to each and every rate for the specified time range.\r\nHere is the list of operations that are currently allowed:\r\n- Add, replace and remove Price\r\n- Add, replace and remove Restrictions<br>You must have this scope: 'rates.manage'.",
          "operationId": "RateplanRatesPatch",
          "security": [
            {
              "oauth2": [
                "rates.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/rate-plans": {
        "get": {
          "tags": [
            "RatePlan"
          ],
          "summary": "Get a rate plan list",
          "description": "Get the list of rate plans depending on client scopes.<br /><br />\r\n            \r\nIf a client has no additional scopes, only public rate plans are returned.<br />\r\nThe 'rateplans.read-corporate' scope adds corporate rate plans to the response.<br>You must have at least one of these scopes: 'rateplans.read, setup.read, setup.manage'.",
          "operationId": "RateplanRate-plansGet",
          "security": [
            {
              "oauth2": [
                "rateplans.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "post": {
          "tags": [
            "RatePlan"
          ],
          "summary": "Create a rate plan",
          "description": "Use this call to create a new rate plan. The rate plan will already contain empty rates, fill them later using PUT rates.<br>You must have at least one of these scopes: 'rateplans.create, setup.manage'.",
          "operationId": "RateplanRate-plansPost",
          "security": [
            {
              "oauth2": [
                "rateplans.create",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "RatePlan"
          ],
          "summary": "Allows to patch one or more rate plans",
          "description": "Here is the list of operations that are currently allowed:\r\n- Replace Name\r\n- Replace Description\r\n- Replace MinGuaranteeType\r\n- Replace PriceCalculationMode\r\n- Replace CancellationPolicy\r\n- Replace NoShowPolicy\r\n- Replace ChannelCodes\r\n- Replace Companies\r\n- Add, replace and remove PromoCode\r\n- Add, replace and remove Restrictions\r\n- Add, replace and remove BookingPeriods\r\n- Add, replace and remove IsSubjectToCityTax\r\n- Add, replace and remove[...]",
          "operationId": "RateplanRate-plansPatch",
          "security": [
            {
              "oauth2": [
                "rateplans.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "RatePlan"
          ],
          "summary": "Delete multiple rate plans",
          "description": "Use this call to delete multiple rate plans.<br>You must have at least one of these scopes: 'rateplans.delete, setup.manage'.",
          "operationId": "RateplanRate-plansDelete",
          "security": [
            {
              "oauth2": [
                "rateplans.delete",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/rate-plans/$count": {
        "get": {
          "tags": [
            "RatePlan"
          ],
          "summary": "Returns number of rate plans",
          "description": "Returns number of rate plans matching the filter criteria, and depending on client scopes<br /><br />\r\n            \r\nIf a client has no additional scopes, only public rate plans are counted.<br />\r\nThe 'rateplans.read-corporate' scope adds corporate rate plans to the result number.<br>You must have at least one of these scopes: 'rateplans.read, setup.read, setup.manage'.",
          "operationId": "RateplanRate-plans$countGet",
          "security": [
            {
              "oauth2": [
                "rateplans.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/rate-plans/{id}": {
        "head": {
          "tags": [
            "RatePlan"
          ],
          "summary": "Check if a rate plan exists",
          "description": "Check if a rate plan exists by id.<br /><br />\r\n            \r\nTo be able to check if a corporate rate plan exists\r\na client must additionaly have 'rateplans.read-corporate' scope assigned.<br>You must have at least one of these scopes: 'rateplans.read, setup.read, setup.manage'.",
          "operationId": "RateplanRate-plansByIdHead",
          "security": [
            {
              "oauth2": [
                "rateplans.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "RatePlan"
          ],
          "summary": "Get a rate plan",
          "description": "Get a rate plan by id.<br /><br />\r\n            \r\nTo be able to read a corporate rate plan a client must additionaly have\r\n'rateplans.read-corporate' scope assigned.<br>You must have at least one of these scopes: 'rateplans.read, setup.read, setup.manage'.",
          "operationId": "RateplanRate-plansByIdGet",
          "security": [
            {
              "oauth2": [
                "rateplans.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "put": {
          "tags": [
            "RatePlan"
          ],
          "summary": "Replace a rate plan",
          "description": "Use this call to modify a rate plan.<br>You must have at least one of these scopes: 'rateplans.manage, setup.manage'.",
          "operationId": "RateplanRate-plansByIdPut",
          "security": [
            {
              "oauth2": [
                "rateplans.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "RatePlan"
          ],
          "summary": "Delete a rate plan",
          "description": "Use this call to delete a rate plan.<br>You must have at least one of these scopes: 'rateplans.delete, setup.manage'.",
          "operationId": "RateplanRate-plansByIdDelete",
          "security": [
            {
              "oauth2": [
                "rateplans.delete",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/rateplan-codes": {
        "get": {
          "tags": [
            "RatePlanCodes"
          ],
          "summary": "Returns a list of rate plan codes.",
          "description": "Returns all existing rate plan codes that match given criteria.<br>You must have at least one of these scopes: 'rateplans.read, setup.read, setup.manage'.",
          "operationId": "RateplanRateplan-codesGet",
          "security": [
            {
              "oauth2": [
                "rateplans.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/services": {
        "post": {
          "tags": [
            "Service"
          ],
          "summary": "Create a service.",
          "description": "Create a service.<br>You must have at least one of these scopes: 'services.create, setup.manage'.",
          "operationId": "RateplanServicesPost",
          "security": [
            {
              "oauth2": [
                "services.create",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "Service"
          ],
          "summary": "Get all services.",
          "description": "Get the list of services.<br>You must have at least one of these scopes: 'services.read, setup.read, setup.manage'.",
          "operationId": "RateplanServicesGet",
          "security": [
            {
              "oauth2": [
                "services.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/services/{id}": {
        "patch": {
          "tags": [
            "Service"
          ],
          "summary": "Modify a service.",
          "description": "Here is the list of operations that are currently allowed:\r\n- Replace Name\r\n- Replace Description\r\n- Replace DefaultGrossPrice\r\n- Replace PricingUnit\r\n- Replace PostNextDay\r\n- Replace Availability\r\n- Add/Replace/Remove/Update AccountingConfigs\r\n- Replace ChannelCodes<br>You must have at least one of these scopes: 'services.manage, setup.manage'.",
          "operationId": "RateplanServicesByIdPatch",
          "security": [
            {
              "oauth2": [
                "services.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "Service"
          ],
          "summary": "Get a specific service.",
          "description": "Get a specific service.<br>You must have at least one of these scopes: 'services.read, setup.read, setup.manage'.",
          "operationId": "RateplanServicesByIdGet",
          "security": [
            {
              "oauth2": [
                "services.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "head": {
          "tags": [
            "Service"
          ],
          "summary": "Check if a service exists",
          "description": "Check if a service exists by id.<br>You must have at least one of these scopes: 'services.read, setup.read, setup.manage'.",
          "operationId": "RateplanServicesByIdHead",
          "security": [
            {
              "oauth2": [
                "services.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "Service"
          ],
          "summary": "Delete a service",
          "description": "Use this call to delete a service.<br>You must have at least one of these scopes: 'services.create, setup.manage'.",
          "operationId": "RateplanServicesByIdDelete",
          "security": [
            {
              "oauth2": [
                "services.create",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/rateplan/v1/services/$count": {
        "get": {
          "tags": [
            "Service"
          ],
          "summary": "Returns number of services.",
          "description": "Returns number of services<br>You must have at least one of these scopes: 'services.read, setup.read, setup.manage'.",
          "operationId": "RateplanServices$countGet",
          "security": [
            {
              "oauth2": [
                "services.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/blocks": {
        "post": {
          "tags": [
            "Block"
          ],
          "summary": "Creates a block",
          "description": "<br>You must have at least one of these scopes: 'blocks.create, reservations.manage'.",
          "operationId": "BookingBlocksPost",
          "security": [
            {
              "oauth2": [
                "blocks.create",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "Block"
          ],
          "summary": "Returns a list of blocks",
          "description": "Returns a list of all blocks, filtered by the specified parameters. If no parameters are set, returns the entire list.<br>You must have at least one of these scopes: 'blocks.read, reservations.read, reservations.manage'.",
          "operationId": "BookingBlocksGet",
          "security": [
            {
              "oauth2": [
                "blocks.read",
                "reservations.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/blocks/$count": {
        "get": {
          "tags": [
            "Block"
          ],
          "summary": "Returns number of blocks",
          "description": "Returns number of blocks matching the filter criteria<br>You must have at least one of these scopes: 'blocks.read, reservations.read, reservations.manage'.",
          "operationId": "BookingBlocks$countGet",
          "security": [
            {
              "oauth2": [
                "blocks.read",
                "reservations.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/blocks/{id}": {
        "get": {
          "tags": [
            "Block"
          ],
          "summary": "Returns a specific block.",
          "description": "Retrieves a block, specified by its ID.<br>You must have at least one of these scopes: 'blocks.read, reservations.read, reservations.manage'.",
          "operationId": "BookingBlocksByIdGet",
          "security": [
            {
              "oauth2": [
                "blocks.read",
                "reservations.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "Block"
          ],
          "summary": "Allows to modify the block [DEPRECATED]",
          "description": "This endpoint is obsolete. It will be removed 10.05.2022. Use `PUT /booking/v1/block-actions/{id}/amend` instead.<br/ >You can replace From, To, GrossDailyRate and BlockedUnits<br>You must have at least one of these scopes: 'blocks.manage, reservations.manage'.",
          "operationId": "BookingBlocksByIdPatch",
          "deprecated": true,
          "security": [
            {
              "oauth2": [
                "blocks.manage",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "Block"
          ],
          "summary": "Delete a specific block",
          "description": "Use this call to delete a block. This is only possible as long as no reservation was picked up yet even if all of\r\nthem are canceled<br>You must have at least one of these scopes: 'blocks.manage, reservations.manage'.",
          "operationId": "BookingBlocksByIdDelete",
          "security": [
            {
              "oauth2": [
                "blocks.manage",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        },
        "head": {
          "tags": [
            "Block"
          ],
          "summary": "Check if a block exists",
          "description": "Check if a block exists by id<br>You must have at least one of these scopes: 'blocks.read, reservations.read, reservations.manage'.",
          "operationId": "BookingBlocksByIdHead",
          "security": [
            {
              "oauth2": [
                "blocks.read",
                "reservations.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/block-actions/{id}/confirm": {
        "put": {
          "tags": [
            "BlockActions"
          ],
          "summary": "Confirm a block.",
          "description": "Confirm a specific block which is in status 'Tentative'.\r\nThis changes the status to 'Definite'.<br>You must have at least one of these scopes: 'blocks.manage, reservations.manage'.",
          "operationId": "BookingBlock-actionsByIdConfirmPut",
          "security": [
            {
              "oauth2": [
                "blocks.manage",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/block-actions/{id}/release": {
        "put": {
          "tags": [
            "BlockActions"
          ],
          "summary": "Release a block.",
          "description": "Release a specific block which is in status 'Definite'.\r\nThis changes the status to 'Tentative'.<br>You must have at least one of these scopes: 'blocks.manage, reservations.manage'.",
          "operationId": "BookingBlock-actionsByIdReleasePut",
          "security": [
            {
              "oauth2": [
                "blocks.manage",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/block-actions/{id}/cancel": {
        "put": {
          "tags": [
            "BlockActions"
          ],
          "summary": "Cancel a block.",
          "description": "Cancel a specific block which is in status 'Definite' or 'Tentative'.\r\nThis changes the status to 'Canceled'.<br>You must have at least one of these scopes: 'blocks.manage, reservations.manage'.",
          "operationId": "BookingBlock-actionsByIdCancelPut",
          "security": [
            {
              "oauth2": [
                "blocks.manage",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/block-actions/{id}/wash": {
        "put": {
          "tags": [
            "BlockActions"
          ],
          "summary": "Wash a block.",
          "description": "Wash a specific block which is in status 'Definite'.\r\nThis releases all unpicked units.<br>You must have at least one of these scopes: 'blocks.manage, reservations.manage'.",
          "operationId": "BookingBlock-actionsByIdWashPut",
          "security": [
            {
              "oauth2": [
                "blocks.manage",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/block-actions/{id}/amend": {
        "put": {
          "tags": [
            "BlockActions"
          ],
          "summary": "Allow to modify a block",
          "description": "Use this call to modify a block.<br>You must have at least one of these scopes: 'blocks.manage, reservations.manage'.",
          "operationId": "BookingBlock-actionsByIdAmendPut",
          "security": [
            {
              "oauth2": [
                "blocks.manage",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/bookings": {
        "post": {
          "tags": [
            "Booking"
          ],
          "summary": "Creates a booking for one or more reservations.",
          "description": "Creates a booking taking a list of reservations as input<br>You must have at least one of these scopes: 'reservations.create, reservations.manage'.",
          "operationId": "BookingBookingsPost",
          "security": [
            {
              "oauth2": [
                "reservations.create",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "Booking"
          ],
          "summary": "Returns a list of all bookings, filtered by the specified parameters.",
          "description": "Returns a list of all bookings, filtered by the specified parameters. If no parameters are set, returns the entire list.<br>You must have at least one of these scopes: 'reservations.read, reservations.manage'.",
          "operationId": "BookingBookingsGet",
          "security": [
            {
              "oauth2": [
                "reservations.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/bookings/$force": {
        "post": {
          "tags": [
            "Booking"
          ],
          "summary": "Creates a booking for one or more reservations regardless of availability or restrictions.",
          "description": "Creates a booking taking a list of reservations as input<br>You must have at least one of these scopes: 'reservations.force-create, reservations.force-manage'.",
          "operationId": "BookingBookings$forcePost",
          "security": [
            {
              "oauth2": [
                "reservations.force-create",
                "reservations.force-manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/bookings/{id}/reservations": {
        "post": {
          "tags": [
            "Booking"
          ],
          "summary": "Add one or multiple reservations to an existing booking.",
          "description": "Creates new reservations and adds them to an existing booking taking a list of reservations as input<br>You must have at least one of these scopes: 'reservations.create, reservations.manage'.",
          "operationId": "BookingBookingsByIdReservationsPost",
          "security": [
            {
              "oauth2": [
                "reservations.create",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/bookings/{id}/reservations/$force": {
        "post": {
          "tags": [
            "Booking"
          ],
          "summary": "Add one or multiple reservations to an existing booking regardless of availability or restrictions.",
          "description": "Creates new reservations and adds them to an existing booking taking a list of reservations as input<br>You must have at least one of these scopes: 'reservations.force-create, reservations.force-manage'.",
          "operationId": "BookingBookingsByIdReservations$forcePost",
          "security": [
            {
              "oauth2": [
                "reservations.force-create",
                "reservations.force-manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/bookings/{id}": {
        "get": {
          "tags": [
            "Booking"
          ],
          "summary": "Returns a specific booking.",
          "description": "Retrieves a booking with all its reservations.<br>You must have at least one of these scopes: 'reservations.read, reservations.manage'.",
          "operationId": "BookingBookingsByIdGet",
          "security": [
            {
              "oauth2": [
                "reservations.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "Booking"
          ],
          "summary": "Allows to modify certain booking properties",
          "description": "Here is the list of operations that are currently allowed:\r\n- Add, replace and remove PaymentAccount\r\n- Add, replace and remove Comment\r\n- Add, replace and remove BookerComment\r\n- Copy PaymentAccount, Comment and BookerComment from the booking to any reservation, or the other way around\r\n- Replace Booker<br>You must have this scope: 'reservations.manage'.",
          "operationId": "BookingBookingsByIdPatch",
          "security": [
            {
              "oauth2": [
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/groups": {
        "post": {
          "tags": [
            "Group"
          ],
          "summary": "Creates a group booking.",
          "description": "<br>You must have at least one of these scopes: 'groups.create, reservations.manage'.",
          "operationId": "BookingGroupsPost",
          "security": [
            {
              "oauth2": [
                "groups.create",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "Group"
          ],
          "summary": "Returns a list of all group bookings, filtered by the specified parameters.",
          "description": "Returns a list of all group bookings, filtered by the specified parameters.\r\nIf no parameters are set, returns the entire list<br>You must have at least one of these scopes: 'groups.read, reservations.read, reservations.manage'.",
          "operationId": "BookingGroupsGet",
          "security": [
            {
              "oauth2": [
                "groups.read",
                "reservations.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/groups/{id}": {
        "get": {
          "tags": [
            "Group"
          ],
          "summary": "Returns a specific group booking.",
          "description": "Retrieves a specific group booking with all its related blocks<br>You must have at least one of these scopes: 'groups.read, reservations.read, reservations.manage'.",
          "operationId": "BookingGroupsByIdGet",
          "security": [
            {
              "oauth2": [
                "groups.read",
                "reservations.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "Group"
          ],
          "summary": "Allows to modify certain group booking properties",
          "description": "Here is the list of operations that are currently allowed:\r\n- Add and replace Name\r\n- Add, replace and remove Comment\r\n- Add, replace and remove BookerComment\r\n- Add, replace and remove PaymentAccount\r\n- Add, replace and remove PropertyIds\r\n- Replace Booker<br>You must have at least one of these scopes: 'groups.manage, reservations.manage'.",
          "operationId": "BookingGroupsByIdPatch",
          "security": [
            {
              "oauth2": [
                "groups.manage",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "Group"
          ],
          "summary": "Delete a certain group booking",
          "description": "Use this call to delete a group booking. This is only possible as long as no blocks exist that are linked to\r\nthis group booking<br>You must have at least one of these scopes: 'groups.manage, reservations.manage'.",
          "operationId": "BookingGroupsByIdDelete",
          "security": [
            {
              "oauth2": [
                "groups.manage",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        },
        "head": {
          "tags": [
            "Group"
          ],
          "summary": "Check if a certain group booking exists",
          "description": "Check if a group booking exists by id<br>You must have at least one of these scopes: 'groups.read, reservations.read, reservations.manage'.",
          "operationId": "BookingGroupsByIdHead",
          "security": [
            {
              "oauth2": [
                "groups.read",
                "reservations.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/groups/$count": {
        "get": {
          "tags": [
            "Group"
          ],
          "summary": "Returns number of group bookings",
          "description": "Returns number of group bookings matching the filter criteria<br>You must have at least one of these scopes: 'groups.read, reservations.read, reservations.manage'.",
          "operationId": "BookingGroups$countGet",
          "security": [
            {
              "oauth2": [
                "groups.read",
                "reservations.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/groups/{id}/reservations": {
        "post": {
          "tags": [
            "Group"
          ],
          "summary": "Add one or multiple reservations to an existing group booking using blocked inventory.",
          "description": "Creates new reservations and adds them to an existing group booking taking a list of reservations as input<br>You must have at least one of these scopes: 'groups.manage, reservations.manage'.",
          "operationId": "BookingGroupsByIdReservationsPost",
          "security": [
            {
              "oauth2": [
                "groups.manage",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/offers": {
        "get": {
          "tags": [
            "Offer"
          ],
          "summary": "Returns offers for one specific stay.",
          "description": "Calculates and returns available offers for a specific property, arrival and departure date.<br>You must have at least one of these scopes: 'offers.read, reservations.manage'.",
          "operationId": "BookingOffersGet",
          "security": [
            {
              "oauth2": [
                "offers.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/rate-plan-offers": {
        "get": {
          "tags": [
            "Offer"
          ],
          "summary": "Returns offers for a specific rate plan.",
          "description": "Calculates and returns available offers for a specific rate plan, arrival and departure date.<br>You must have at least one of these scopes: 'offers.read, reservations.manage'.",
          "operationId": "BookingRate-plan-offersGet",
          "security": [
            {
              "oauth2": [
                "offers.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/service-offers": {
        "get": {
          "tags": [
            "Offer"
          ],
          "summary": "Returns service offers for one specific stay.",
          "description": "<br>You must have at least one of these scopes: 'offers.read, reservations.manage'.",
          "operationId": "BookingService-offersGet",
          "security": [
            {
              "oauth2": [
                "offers.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/offer-index": {
        "get": {
          "tags": [
            "Offer"
          ],
          "summary": "Returns offers with rates and availabilities for the specified range.",
          "description": "Calculates and returns offers per time slice for a specific rate plan, arrival and departure date.<br>You must have at least one of these scopes: 'offer-index.read, offers.read'.",
          "operationId": "BookingOffer-indexGet",
          "security": [
            {
              "oauth2": [
                "offer-index.read",
                "offers.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservations": {
        "get": {
          "tags": [
            "Reservation"
          ],
          "summary": "Returns a list of all reservations, filtered by the specified parameters.",
          "description": "Returns a list of all reservations, filtered by the specified parameters. If no parameters are set, returns the entire list.<br>You must have at least one of these scopes: 'reservations.read, reservations.manage'.",
          "operationId": "BookingReservationsGet",
          "security": [
            {
              "oauth2": [
                "reservations.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservations/$count": {
        "get": {
          "tags": [
            "Reservation"
          ],
          "summary": "Returns the number of reservations fulfilling the criteria specified in the parameters.",
          "description": "If no parameters are set, returns the total count of reservations.<br>You must have at least one of these scopes: 'reservations.read, reservations.manage'.",
          "operationId": "BookingReservations$countGet",
          "security": [
            {
              "oauth2": [
                "reservations.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservations/{id}": {
        "get": {
          "tags": [
            "Reservation"
          ],
          "summary": "Returns a specific reservation.",
          "description": "Retrieves a reservation, specified by its ID.<br>You must have at least one of these scopes: 'reservations.read, reservations.manage'.",
          "operationId": "BookingReservationsByIdGet",
          "security": [
            {
              "oauth2": [
                "reservations.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "Reservation"
          ],
          "summary": "Allows to modify certain reservation properties",
          "description": "Here is the list of operations that are currently allowed:\r\n- Add, replace and remove Comment\r\n- Add, replace and remove GuestComment\r\n- Add, replace and remove PaymentAccount\r\n- Add, replace and remove TravelPurpose\r\n- Add, replace and remove AdditionalGuests\r\n- Add a company (using company/Id, and only if not already set)\r\n- Add, replace and remove Commission\r\n- Replace PrimaryGuest\r\n- Remove ValidationMessages<br>You must have this scope: 'reservati[...]",
          "operationId": "BookingReservationsByIdPatch",
          "security": [
            {
              "oauth2": [
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservations/{id}/offers": {
        "get": {
          "tags": [
            "Reservation"
          ],
          "summary": "Returns offers for one specific reservation.",
          "description": "Calculates and returns offers for amending a specific reservation.<br>You must have at least one of these scopes: 'offers.read, reservations.manage'.",
          "operationId": "BookingReservationsByIdOffersGet",
          "security": [
            {
              "oauth2": [
                "offers.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservations/{id}/service-offers": {
        "get": {
          "tags": [
            "Reservation"
          ],
          "summary": "Returns service offers for one specific reservation.",
          "description": "Calculates and returns service offers for a specific reservation.<br>You must have at least one of these scopes: 'offers.read, reservations.manage'.",
          "operationId": "BookingReservationsByIdService-offersGet",
          "security": [
            {
              "oauth2": [
                "offers.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservations/{id}/services": {
        "get": {
          "tags": [
            "Reservation"
          ],
          "summary": "Returns the services booked for a specific reservation.",
          "description": "Returns the services booked for a specific reservation.<br>You must have at least one of these scopes: 'reservations.read, reservations.manage'.",
          "operationId": "BookingReservationsByIdServicesGet",
          "security": [
            {
              "oauth2": [
                "reservations.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "Reservation"
          ],
          "summary": "Removes a service from a reservation.",
          "description": "Removes a service from a reservation. The service will not be removed if it is mandatory, already posted or if the service date is in the past.<br>You must have this scope: 'reservations.manage'.",
          "operationId": "BookingReservationsByIdServicesDelete",
          "security": [
            {
              "oauth2": [
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservation-actions/{id}/assign-unit": {
        "put": {
          "tags": [
            "ReservationActions"
          ],
          "summary": "Assign a unit to a reservation.",
          "description": "Assigns one of the available units to a reservation which is in state 'Confirmed' or 'InHouse'.<br>You must have at least one of these scopes: 'reservations.assign-unit, reservations.manage'.",
          "operationId": "BookingReservation-actionsByIdAssign-unitPut",
          "security": [
            {
              "oauth2": [
                "reservations.assign-unit",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservation-actions/{id}/assign-unit/{unitId}": {
        "put": {
          "tags": [
            "ReservationActions"
          ],
          "summary": "Assign a specific unit to a reservation.",
          "description": "Assigns a specific unit to a reservation which is in state 'Confirmed' or 'InHouse'.<br />If the unit is not available, the call will return an error, and no unit will be assigned.<br>You must have at least one of these scopes: 'reservations.assign-unit, reservations.manage'.",
          "operationId": "BookingReservation-actionsByIdAssign-unitByUnitIdPut",
          "security": [
            {
              "oauth2": [
                "reservations.assign-unit",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservation-actions/{id}/unassign-units": {
        "put": {
          "tags": [
            "ReservationActions"
          ],
          "summary": "Unassign units from a reservation.",
          "description": "Unassigns units for all time slices of the given reservation. If no units are assigned for the\r\nreservation nothing will happen. It will fail for reservations in status 'CheckedOut'.<br>You must have at least one of these scopes: 'reservations.assign-unit, reservations.manage'.",
          "operationId": "BookingReservation-actionsByIdUnassign-unitsPut",
          "security": [
            {
              "oauth2": [
                "reservations.assign-unit",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservation-actions/{id}/checkin": {
        "put": {
          "tags": [
            "ReservationActions"
          ],
          "summary": "Check-in of a reservation.",
          "description": "Check in a specific reservation which is in status 'Confirmed', and has a unit assigned. This changes the status to 'InHouse', and sets the check-in date and time.<br>You must have this scope: 'reservations.manage'.",
          "operationId": "BookingReservation-actionsByIdCheckinPut",
          "security": [
            {
              "oauth2": [
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservation-actions/{id}/checkout": {
        "put": {
          "tags": [
            "ReservationActions"
          ],
          "summary": "Check-out of a reservation.",
          "description": "Check out a specific reservation which is in status 'InHouse'. This changes the status to 'CheckedOut', and sets the check-out date and time.\r\nAll open charges on the folio will be posted.\r\n<br />\r\nCheck-out is only possible, if the departure date is not later than tomorrow. Otherwise, first amend the reservation and shorten the stay.<br>You must have this scope: 'reservations.manage'.",
          "operationId": "BookingReservation-actionsByIdCheckoutPut",
          "security": [
            {
              "oauth2": [
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservation-actions/{id}/cancel": {
        "put": {
          "tags": [
            "ReservationActions"
          ],
          "summary": "Cancel a reservation.",
          "description": "Cancel a specific reservation which is in status 'Confirmed' and where the arrival time is in the future.\r\nThis changes the status to 'Canceled', and sets the cancellation date and time.<br>You must have this scope: 'reservations.manage'.",
          "operationId": "BookingReservation-actionsByIdCancelPut",
          "security": [
            {
              "oauth2": [
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservation-actions/{id}/noshow": {
        "put": {
          "tags": [
            "ReservationActions"
          ],
          "summary": "Set a reservation to No-show.",
          "description": "Set a specific reservation to No-show which is in status 'Confirmed' and where the arrival date is in the past.\r\nThis changes the status to 'NoShow', and sets the no-show date and time.<br>You must have this scope: 'reservations.manage'.",
          "operationId": "BookingReservation-actionsByIdNoshowPut",
          "security": [
            {
              "oauth2": [
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservation-actions/{id}/amend": {
        "put": {
          "tags": [
            "ReservationActions"
          ],
          "summary": "Allows you to amend the stay details of a reservation",
          "description": "Modifies the stay-related data of a reservation.<br />\r\nIf a reservation is 'Confirmed', you can change all fields.<br />\r\nIf a reservation is 'InHouse', only changes to future time slices are possible.<br />\r\nChanges to reservations that are in the status 'CheckedOut' or 'Canceled' are not possible at all.<br>You must have this scope: 'reservations.manage'.",
          "operationId": "BookingReservation-actionsByIdAmendPut",
          "security": [
            {
              "oauth2": [
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservation-actions/{id}/amend/$force": {
        "put": {
          "tags": [
            "ReservationActions"
          ],
          "summary": "Allows you to amend the stay details of a reservation regardless of availability or restrictions.",
          "description": "Modifies the stay-related data of a reservation.<br />\r\nIf a reservation is 'Confirmed', you can change all fields.<br />\r\nIf a reservation is 'InHouse', only changes to future time slices are possible.<br />\r\nChanges to reservations that are in the status 'CheckedOut' or 'Canceled' are not possible at all.<br>You must have this scope: 'reservations.force-manage'.",
          "operationId": "BookingReservation-actionsByIdAmend$forcePut",
          "security": [
            {
              "oauth2": [
                "reservations.force-manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservation-actions/{id}/book-service": {
        "put": {
          "tags": [
            "ReservationActions"
          ],
          "summary": "Book the service for a specific reservation.",
          "description": "Use this to book a service for a specific reservation.\r\nPlease note that when dates are specified, all desired dates must be specified or they will be removed if not posted to the folio.<br>You must have this scope: 'reservations.manage'.",
          "operationId": "BookingReservation-actionsByIdBook-servicePut",
          "security": [
            {
              "oauth2": [
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservation-actions/{id}/book-service/$force": {
        "put": {
          "tags": [
            "ReservationActions"
          ],
          "summary": "Book the service for a specific reservation regardless of availability.",
          "description": "Use this to book a service for a specific reservation.\r\nPlease note that when dates are specified, all desired dates must be specified or they will be removed if not posted to the folio.<br>You must have this scope: 'reservations.manage'.",
          "operationId": "BookingReservation-actionsByIdBook-service$forcePut",
          "security": [
            {
              "oauth2": [
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservation-actions/{id}/remove-city-tax": {
        "put": {
          "tags": [
            "ReservationActions"
          ],
          "summary": "Removes the city tax from a reservation.",
          "description": "Use this is you want to remove the city tax from a reservation before the stay.<br>You must have this scope: 'reservations.manage'.",
          "operationId": "BookingReservation-actionsByIdRemove-city-taxPut",
          "security": [
            {
              "oauth2": [
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/reservation-actions/{id}/add-city-tax": {
        "put": {
          "tags": [
            "ReservationActions"
          ],
          "summary": "Adds the city tax to a reservation.",
          "description": "Use this if you want to add the city tax to a reservation.<br>You must have this scope: 'reservations.manage'.",
          "operationId": "BookingReservation-actionsByIdAdd-city-taxPut",
          "security": [
            {
              "oauth2": [
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/booking/v1/types/sources": {
        "get": {
          "tags": [
            "Types"
          ],
          "summary": "Returns a list of supported sources.",
          "description": "Returns a list of channels that could be used as a source to create bookings.",
          "operationId": "BookingTypesSourcesGet"
        }
      },
      "/finance/v1/folios": {
        "get": {
          "tags": [
            "Folio"
          ],
          "summary": "Returns a list of all folios.",
          "description": "Allowed actions are only returned, when the list is filtered by reservation ID.<br>You must have at least one of these scopes: 'folios.read, folios.manage'.",
          "operationId": "FinanceFoliosGet",
          "security": [
            {
              "oauth2": [
                "folios.read",
                "folios.manage",
                "admin"
              ]
            }
          ]
        },
        "post": {
          "tags": [
            "Folio"
          ],
          "summary": "Create additional folios for a reservation, or new external folios",
          "description": "Use this call to create a new folio.<br>You must have at least one of these scopes: 'reservations.create, reservations.manage, folios.manage'.",
          "operationId": "FinanceFoliosPost",
          "security": [
            {
              "oauth2": [
                "reservations.create",
                "reservations.manage",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folios/$count": {
        "get": {
          "tags": [
            "Folio"
          ],
          "summary": "Returns number of folios.",
          "description": "Returns number of folios matching the filter criteria.<br>You must have at least one of these scopes: 'folios.read, folios.manage'.",
          "operationId": "FinanceFolios$countGet",
          "security": [
            {
              "oauth2": [
                "folios.read",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folios/{id}": {
        "get": {
          "tags": [
            "Folio"
          ],
          "summary": "Returns one folio.",
          "description": "Get a folio by ID.<br>You must have at least one of these scopes: 'folios.read, folios.manage'.",
          "operationId": "FinanceFoliosByIdGet",
          "security": [
            {
              "oauth2": [
                "folios.read",
                "folios.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "Folio"
          ],
          "summary": "Allows to modify certain properties of a folio",
          "description": "Here is the list of operations that are currently allowed:\r\n- Replace debitor (for guest folios only)\r\n- Add a company (not for house folios)\r\n- Replace/remove a company (not for house folios)<br>You must have this scope: 'folios.manage'.",
          "operationId": "FinanceFoliosByIdPatch",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        },
        "head": {
          "tags": [
            "Folio"
          ],
          "summary": "Check if the folio exists.",
          "description": "Check if the folio exists.<br>You must have at least one of these scopes: 'folios.read, folios.manage'.",
          "operationId": "FinanceFoliosByIdHead",
          "security": [
            {
              "oauth2": [
                "folios.read",
                "folios.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "Folio"
          ],
          "summary": "Deletes a folio.",
          "description": "Deletes a folio. This cannot be undone.\r\nYou can delete a folio only if it's not a main folio,\r\nand the folio is empty (it has no charges, allowance, payments or pending payments).\r\n<br />\r\nRequires 'allowed action': Delete.<br>You must have this scope: 'folios.manage'.",
          "operationId": "FinanceFoliosByIdDelete",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/charges": {
        "post": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Adds and directly posts a charge to the folio.\r\nIf there are any fees configured for the property, an additional charge for each configured fee will be added.",
          "description": "Adds a charge for any good or service, and directly posts it. Can be used to charge items that are not part of the reservation,\r\nbut should appear on the invoice.\r\n<br />\r\nRequires 'allowed action': AddCharge.<br>You must have at least one of these scopes: 'charges.create, folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdChargesPost",
          "security": [
            {
              "oauth2": [
                "charges.create",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/transitory-charges": {
        "post": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Adds and directly posts a transitory charge to the folio.\r\nIf there are any fees configured for the property, an additional charge for each configured fee will be added.",
          "description": "Adds a transitory item for any good or service, and directly posts it. To be used for sales that are not revenue of the property,\r\nbut should appear on te guest's invoice.\r\n<br />\r\nRequires 'allowed action': AddCharge.<br>You must have at least one of these scopes: 'charges.create, folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdTransitory-chargesPost",
          "security": [
            {
              "oauth2": [
                "charges.create",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/cancellation-fee": {
        "post": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Adds and directly posts a cancellation fee to the folio.\r\nIf there are any fees configured for the property, an additional charge for each configured fee will be added.",
          "description": "Adds a cancellation fee, and directly posts it. Cancellation fees can only be posted on guest folios.\r\n<br />\r\nRequires 'allowed action': AddCancellationFee.<br>You must have at least one of these scopes: 'charges.create, folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdCancellation-feePost",
          "security": [
            {
              "oauth2": [
                "charges.create",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/no-show-fee": {
        "post": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Adds and directly posts a no-show fee to the folio.\r\nIf there are any fees configured for the property, an additional charge for each configured fee will be added.",
          "description": "Adds a no-show fee, and directly posts it. No-show fees can only be posted on guest folios.\r\n<br />\r\nRequires 'allowed action': AddNoShowFee.<br>You must have at least one of these scopes: 'charges.create, folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdNo-show-feePost",
          "security": [
            {
              "oauth2": [
                "charges.create",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/close": {
        "put": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Closes a folio.",
          "description": "Mark a folio as closed to prevent adding charges and payments. This action cannot be undone,\r\nand is only possible if the balance is 0.\r\n<br />\r\nRequires 'allowed action': Close.<br>You must have this scope: 'folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdClosePut",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/reopen": {
        "put": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Reopens a folio.",
          "description": "Reopens a closed folio.\r\nYou can only reopen a folio if no invoice has been created for the folio.\r\nOtherwise, use `invoice-actions/{invoiceId}/cancel` endpoint to cancel an invoice and reopen the folio.\r\n<br />\r\nRequires 'allowed action': Reopen.<br>You must have this scope: 'folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdReopenPut",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/move-charges": {
        "put": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Move multiple charges, allowances and transitory charges from one folio to another.",
          "description": "If one of the folios is closed, this action cannot be performed.<br /><br />\r\nIf any of the specified charges does not exist, this action cannot be performed.<br /><br />\r\nMoving negative charges to a house folio is not supported. Create additional folios instead, and move the charges there.<br>You must have at least one of these scopes: 'charges.move, folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdMove-chargesPut",
          "security": [
            {
              "oauth2": [
                "charges.move",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/bulk-move": {
        "put": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Move multiple charges from one folio to another. Multiple source folios and multiple target folios can be specified.",
          "description": "If one of the folios is closed, this action cannot be performed.<br /><br />\r\nIf any of the specified charges does not exist, this action cannot be performed.<br /><br />\r\nMoving negative charges to a house folio is not supported. Create additional folios instead, and move the charges there.<br>You must have this scope: 'folios.manage'.",
          "operationId": "FinanceFolio-actionsBulk-movePut",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/move-all-charges": {
        "put": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Move all charges and transitory charges from one folio to another.",
          "description": "If one of the folios is closed, this action cannot be performed.<br /><br />\r\nOnly charges that can be moved will be moved.<br /><br /><br>You must have at least one of these scopes: 'charges.move, folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdMove-all-chargesPut",
          "security": [
            {
              "oauth2": [
                "charges.move",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/charges/{chargeId}/allowances": {
        "post": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Posts an allowance for a charge",
          "description": "Allowance value posted must not exceed source charge minus allowances posted for this charge<br>You must have at least one of these scopes: 'allowances.post, folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdChargesByChargeIdAllowancesPost",
          "security": [
            {
              "oauth2": [
                "allowances.post",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/allowances": {
        "post": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Posts an allowance for a folio",
          "description": "Allowance value posted must not exceed sum of charges minus existing allowances<br>You must have at least one of these scopes: 'allowances.post, folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdAllowancesPost",
          "security": [
            {
              "oauth2": [
                "allowances.post",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/bulk-allowances": {
        "post": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Posts allowances for a folio",
          "description": "Allowance value posted must not exceed sum of charges minus existing allowances<br>You must have at least one of these scopes: 'allowances.post, folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdBulk-allowancesPost",
          "security": [
            {
              "oauth2": [
                "allowances.post",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/post-charges": {
        "put": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Posts all unposted charges for the whole length of stay.",
          "description": "Use this call for cases when the folio should be closed early. For example, when a guest wants to get the invoice right after the check-in\r\nAs posting charges before the service is delivered is potentially risky, this operation will fail if there are any unposted charges\r\nfurther in the future than 7 days.\r\nPosting open charges is only possible for fully prepaid folios.\r\n<br />\r\nRequires 'allowed action': PostOpenCharges.<br>You must have this scope: 'folios.m[...]",
          "operationId": "FinanceFolio-actionsByFolioIdPost-chargesPut",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/move-payments": {
        "put": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Move multiple payments from one folio of a reservation to another.",
          "description": "Move payments from one folio of a reservation to another - moving between different reservations is not supported,\r\nand will lead to an error. If one of the folios is closed, this action cannot be performed.<br />\r\nThe PSP reference, if present, will be removed when moving and only be persisted on the original payment.<br>You must have at least one of these scopes: 'charges.move, folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdMove-paymentsPut",
          "security": [
            {
              "oauth2": [
                "charges.move",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/correct": {
        "post": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Corrects a folio by moving some charges.\r\nThis operation creates a new folio with the charges from the request.\r\nThe payment, equal to the sum of charges, is also split to this new folio so that both folios will have 0 balance.",
          "description": "Allowance value posted must not exceed sum of charges minus existing allowances<br>You must have this scope: 'folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdCorrectPost",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/charges/{chargeId}/split": {
        "post": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Splits a charge into two using the percent or amount provided\r\nCreates an allowance and two new charges.",
          "description": "<br>You must have at least one of these scopes: 'allowances.post, charges.create, folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdChargesByChargeIdSplitPost",
          "security": [
            {
              "oauth2": [
                "allowances.post",
                "charges.create",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folio-actions/{folioId}/payments/{paymentId}/split": {
        "post": {
          "tags": [
            "FolioActions"
          ],
          "summary": "Splits a payment into two using the percent or amount provided\r\nCreates a refund and two new payments.",
          "description": "<br>You must have at least one of these scopes: 'payments.create, refunds.create, folios.manage'.",
          "operationId": "FinanceFolio-actionsByFolioIdPaymentsByPaymentIdSplitPost",
          "security": [
            {
              "oauth2": [
                "payments.create",
                "refunds.create",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folios/{folioId}/payments": {
        "get": {
          "tags": [
            "FolioPayments"
          ],
          "summary": "Get a list of payments.",
          "description": "Returns a list of all payments for this folio ordered by creation date, newest first<br>You must have at least one of these scopes: 'folios.read, folios.manage'.",
          "operationId": "FinanceFoliosByFolioIdPaymentsGet",
          "security": [
            {
              "oauth2": [
                "folios.read",
                "folios.manage",
                "admin"
              ]
            }
          ]
        },
        "post": {
          "tags": [
            "FolioPayments"
          ],
          "summary": "Trigger a custom payment for the folio.",
          "description": "A custom payment will not involve any automatic processing. This is best to be used for cash, cheque or voucher payments or payments that have\r\nbeen processed by an external system and it should just be recorded in apaleo for accounting purposes.<br>You must have this scope: 'folios.manage'.",
          "operationId": "FinanceFoliosByFolioIdPaymentsPost",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folios/{folioId}/payments/{paymentId}": {
        "get": {
          "tags": [
            "FolioPayments"
          ],
          "summary": "Get a payment by ID.",
          "description": "Get a payment by its ID<br>You must have at least one of these scopes: 'folios.read, folios.manage'.",
          "operationId": "FinanceFoliosByFolioIdPaymentsByPaymentIdGet",
          "security": [
            {
              "oauth2": [
                "folios.read",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folios/{folioId}/payments/by-terminal": {
        "post": {
          "tags": [
            "FolioPayments"
          ],
          "summary": "Trigger a payment on a card terminal for the folio.",
          "description": "Trigger a terminal payment for the folio. The payment will be processed asynchronously. Use the location header to poll for the status of the payment.\r\nAs long as a payment is pending it reduces the amount of allowed payments for the folio. The payment times out after 60 minutes automatically<br>You must have this scope: 'folios.manage'.",
          "operationId": "FinanceFoliosByFolioIdPaymentsBy-terminalPost",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folios/{folioId}/payments/by-authorization": {
        "post": {
          "tags": [
            "FolioPayments"
          ],
          "summary": "Captures a specific amount from a pre-authorization and posts it to the folio.",
          "description": "Captures a specific amount from a pre-authorization and posts it to the folio. For the pre-authorization please ensure to set the respective metadata in the original payment\r\ntransaction. The flow type has to be set to <i>CaptureOnly</i>. For more information please refer to the documentation of <a href=\"https://apaleo.dev/guides/business-cases/ibe/getting-the-money\" target=\"_blank\">how to do a pre-authorization on a booking engine</a>.\r\nThe payment will be proc[...]",
          "operationId": "FinanceFoliosByFolioIdPaymentsBy-authorizationPost",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folios/{folioId}/payments/by-payment-account": {
        "post": {
          "tags": [
            "FolioPayments"
          ],
          "summary": "Trigger a payment using the payment account stored on the reservation.",
          "description": "Trigger a payment for the folio using the payment account stored on the reservation. The payment will be processed asynchronously. Use the location header to poll\r\nfor the status of the payment. As long as a payment is pending it reduces the amount of allowed payments for the folio. The payment times out after 60 minutes\r\nautomatically<br>You must have this scope: 'folios.manage'.",
          "operationId": "FinanceFoliosByFolioIdPaymentsBy-payment-accountPost",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folios/{folioId}/payments/by-link": {
        "post": {
          "tags": [
            "FolioPayments"
          ],
          "summary": "Creates a link to a payment form where guests can pay.",
          "description": "Creates a link to a payment form where guests can pay. To enable open invoice payment methods you need to provide at\r\nleast the paid charges with the request. For some open invoice payment methods you also need to ensure that the full\r\nbilling address of the folio is set, before you create the payment link. The payment will be processed asynchronously.\r\nUse the location header to poll for the status of the payment. As long as a payment is pending it reduces the am[...]",
          "operationId": "FinanceFoliosByFolioIdPaymentsBy-linkPost",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folios/{folioId}/payments/{paymentId}/cancel": {
        "put": {
          "tags": [
            "FolioPayments"
          ],
          "summary": "Cancels a payment.",
          "description": "Sets a payment to cancelled and triggers the cancellation.<br>You must have this scope: 'folios.manage'.",
          "operationId": "FinanceFoliosByFolioIdPaymentsByPaymentIdCancelPut",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folios/{folioId}/refunds": {
        "get": {
          "tags": [
            "FolioPayments"
          ],
          "summary": "Get a list of refunds.",
          "description": "Returns a list of all refunds for this folio ordered by creation date, newest first<br>You must have at least one of these scopes: 'folios.read, folios.manage'.",
          "operationId": "FinanceFoliosByFolioIdRefundsGet",
          "security": [
            {
              "oauth2": [
                "folios.read",
                "folios.manage",
                "admin"
              ]
            }
          ]
        },
        "post": {
          "tags": [
            "FolioPayments"
          ],
          "summary": "Trigger a refund for the folio.",
          "description": "Trigger a generic refund for the folio. The refund will be processed asynchronously. Use the location header to poll for the status of the refund.\r\nAs long as a refund is pending it reduces the amount of allowed refunds for the folio. The refund times out after 60 minutes automatically<br>You must have this scope: 'folios.manage'.",
          "operationId": "FinanceFoliosByFolioIdRefundsPost",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folios/{folioId}/refunds/{refundId}": {
        "get": {
          "tags": [
            "FolioPayments"
          ],
          "summary": "Get a refund by ID.",
          "description": "Get a refund by its ID<br>You must have at least one of these scopes: 'folios.read, folios.manage'.",
          "operationId": "FinanceFoliosByFolioIdRefundsByRefundIdGet",
          "security": [
            {
              "oauth2": [
                "folios.read",
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/folios/{folioId}/payments/{paymentId}/refunds": {
        "post": {
          "tags": [
            "FolioPayments"
          ],
          "summary": "Trigger a refund for a specific payment.",
          "description": "Trigger a refund for a specific payment on this folio. The refund will be processed asynchronously. Use the location header to poll for\r\nthe status of the refund. As long as a refund is pending the allowed refund amount for this payment will be reduced by the amount. The refund\r\ntimes out after 10 minutes automatically<br>You must have this scope: 'folios.manage'.",
          "operationId": "FinanceFoliosByFolioIdPaymentsByPaymentIdRefundsPost",
          "security": [
            {
              "oauth2": [
                "folios.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/invoices/preview-pdf": {
        "get": {
          "tags": [
            "Invoice"
          ],
          "summary": "Gets a preview invoice PDF for one specific folio.",
          "description": "Gets a preview invoice PDF for one specific folio.<br>You must have this scope: 'invoices.read'.",
          "operationId": "FinanceInvoicesPreview-pdfGet",
          "security": [
            {
              "oauth2": [
                "invoices.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/invoices/preview": {
        "get": {
          "tags": [
            "Invoice"
          ],
          "summary": "Gets an invoice preview for one specific folio.",
          "description": "To see if the invoice creation would be successful, check the warnings.<br>You must have this scope: 'invoices.read'.",
          "operationId": "FinanceInvoicesPreviewGet",
          "security": [
            {
              "oauth2": [
                "invoices.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/invoices": {
        "get": {
          "tags": [
            "Invoice"
          ],
          "summary": "Gets the list of all invoices (the metadata only, not the files).",
          "description": "Gets the list of all invoices (the metadata only, not the files).<br>You must have this scope: 'invoices.read'.",
          "operationId": "FinanceInvoicesGet",
          "security": [
            {
              "oauth2": [
                "invoices.read",
                "admin"
              ]
            }
          ]
        },
        "post": {
          "tags": [
            "Invoice"
          ],
          "summary": "Creates an invoice for one specific folio.",
          "description": "Creates an invoice for one specific folio. The invoice can only be created once.\r\nThe debitor needs to have name, city, postal code and country code, as these are required for invoices.\r\nIf the folio is not fully paid, this will check out the reservation on AR and create an invoice with outstanding payments.<br>You must have at least one of these scopes: 'invoices.create, invoices.manage'.",
          "operationId": "FinanceInvoicesPost",
          "security": [
            {
              "oauth2": [
                "invoices.create",
                "invoices.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/invoices/{id}/pdf": {
        "get": {
          "tags": [
            "Invoice"
          ],
          "summary": "Gets an invoice PDF file.",
          "description": "Gets an invoice PDF file by its ID. Only works for invoices that have already been created using POST /invoices.<br>You must have this scope: 'invoices.read'.",
          "operationId": "FinanceInvoicesByIdPdfGet",
          "security": [
            {
              "oauth2": [
                "invoices.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/invoices/{id}": {
        "get": {
          "tags": [
            "Invoice"
          ],
          "summary": "Gets invoice data.",
          "description": "Gets invoice data by its ID. Only works for invoices that have already been created using POST /invoices.<br>You must have this scope: 'invoices.read'.",
          "operationId": "FinanceInvoicesByIdGet",
          "security": [
            {
              "oauth2": [
                "invoices.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/invoice-actions/{id}/pay": {
        "put": {
          "tags": [
            "InvoiceAction"
          ],
          "summary": "Marks an invoice as paid.",
          "description": "Settles the invoice, if the invoice has an amount to be paid (total != 0).<br>You must have this scope: 'invoices.manage'.",
          "operationId": "FinanceInvoice-actionsByIdPayPut",
          "security": [
            {
              "oauth2": [
                "invoices.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/invoice-actions/{id}/cancel": {
        "put": {
          "tags": [
            "InvoiceAction"
          ],
          "summary": "Cancels an invoice",
          "description": "For regular invoices and AR invoices that haven't been paid yet, creates a new cancellation invoice and opens the folio again.\r\nFor advance invoices, creates a new cancellation invoice.<br>You must have this scope: 'invoices.manage'.",
          "operationId": "FinanceInvoice-actionsByIdCancelPut",
          "security": [
            {
              "oauth2": [
                "invoices.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/accounts/aggregate-pairs-daily": {
        "post": {
          "tags": [
            "SubLedger"
          ],
          "summary": "Aggregates transactions pairs by date (business day) for all accounts and a given period.",
          "description": "Returns total amount credited from one account to another<br>You must have at least one of these scopes: 'subledger.read, accounting.read'.",
          "operationId": "FinanceAccountsAggregate-pairs-dailyPost",
          "security": [
            {
              "oauth2": [
                "subledger.read",
                "accounting.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/accounts/aggregate-daily": {
        "post": {
          "tags": [
            "SubLedger"
          ],
          "summary": "Aggregates transactions by date (business day) for all accounts and a given period.",
          "description": "Returns credited and debited amounts aggregated by transactions' date (business day) for all accounts and a given period.\r\nStores an entry in the export audit log.<br>You must have at least one of these scopes: 'subledger.read, accounting.read'.",
          "operationId": "FinanceAccountsAggregate-dailyPost",
          "security": [
            {
              "oauth2": [
                "subledger.read",
                "accounting.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/accounts/aggregate": {
        "post": {
          "tags": [
            "SubLedger"
          ],
          "summary": "Aggregates transactions by timestamp for all accounts and a given period.",
          "description": "Returns credited and debited amounts aggregated by transactions' timestamp for all accounts and a given period.\r\nStores an entry in the export audit log.<br>You must have at least one of these scopes: 'subledger.read, accounting.read'.",
          "operationId": "FinanceAccountsAggregatePost",
          "security": [
            {
              "oauth2": [
                "subledger.read",
                "accounting.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/accounts/export": {
        "post": {
          "tags": [
            "SubLedger"
          ],
          "summary": "Returns transactions filtered by timestamp for a property for a given period.",
          "description": "Returns the raw transaction data for a given property and time period.\r\nStores an entry in the export audit log.<br>You must have at least one of these scopes: 'transactions.export, accounting.read'.",
          "operationId": "FinanceAccountsExportPost",
          "security": [
            {
              "oauth2": [
                "transactions.export",
                "accounting.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/accounts/export-daily": {
        "post": {
          "tags": [
            "SubLedger"
          ],
          "summary": "Returns transactions filtered by date (business day) for a property for a given period.",
          "description": "Returns the raw transaction data for a given property and time period.\r\nStores an entry in the export audit log.<br>You must have at least one of these scopes: 'transactions.export, accounting.read'.",
          "operationId": "FinanceAccountsExport-dailyPost",
          "security": [
            {
              "oauth2": [
                "transactions.export",
                "accounting.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/accounts/export-gross-daily": {
        "post": {
          "tags": [
            "SubLedger"
          ],
          "summary": "Returns gross transactions filtered by date (business day) for a property for a given period.",
          "description": "Returns the raw transaction data for a given property and time period.\r\nStores an entry in the export audit log.<br>You must have at least one of these scopes: 'transactions.export, accounting.read'.",
          "operationId": "FinanceAccountsExport-gross-dailyPost",
          "security": [
            {
              "oauth2": [
                "transactions.export",
                "accounting.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/accounts/schema": {
        "get": {
          "tags": [
            "SubLedger"
          ],
          "summary": "Returns the chart of accounts of the subledger.",
          "description": "Returns the schema of subledger, split into global and guest ledger.<br>You must have at least one of these scopes: 'subledger.read, accounting.read'.",
          "operationId": "FinanceAccountsSchemaGet",
          "security": [
            {
              "oauth2": [
                "subledger.read",
                "accounting.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/global-accounts": {
        "get": {
          "tags": [
            "SubLedger"
          ],
          "summary": "Returns a list of global accounts.",
          "description": "Returns a list of accounts in one property, having the same global account as parent.<br>You must have at least one of these scopes: 'subledger.read, accounting.read'.",
          "operationId": "FinanceGlobal-accountsGet",
          "security": [
            {
              "oauth2": [
                "subledger.read",
                "accounting.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/guest-accounts": {
        "get": {
          "tags": [
            "SubLedger"
          ],
          "summary": "Returns a list of guest accounts.",
          "description": "Returns a list of accounts in one property for a reservation.<br>You must have at least one of these scopes: 'subledger.read, accounting.read'.",
          "operationId": "FinanceGuest-accountsGet",
          "security": [
            {
              "oauth2": [
                "subledger.read",
                "accounting.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/external-accounts": {
        "get": {
          "tags": [
            "SubLedger"
          ],
          "summary": "Returns a list of external accounts.",
          "description": "Returns a list of accounts in one property for a folio.<br>You must have at least one of these scopes: 'subledger.read, accounting.read'.",
          "operationId": "FinanceExternal-accountsGet",
          "security": [
            {
              "oauth2": [
                "subledger.read",
                "accounting.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/accounts/{number}": {
        "get": {
          "tags": [
            "SubLedger"
          ],
          "summary": "Returns one account.",
          "description": "Returns one account, as specified by its number and the property.<br>You must have at least one of these scopes: 'subledger.read, accounting.read'.",
          "operationId": "FinanceAccountsByNumberGet",
          "security": [
            {
              "oauth2": [
                "subledger.read",
                "accounting.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/accounts/child-accounts": {
        "get": {
          "tags": [
            "SubLedger"
          ],
          "summary": "Returns a list of child accounts for a specified parent account.",
          "description": "<br>You must have at least one of these scopes: 'subledger.read, accounting.read'.",
          "operationId": "FinanceAccountsChild-accountsGet",
          "security": [
            {
              "oauth2": [
                "subledger.read",
                "accounting.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/finance/v1/types/currencies": {
        "get": {
          "tags": [
            "Types"
          ],
          "summary": "Returns a list of all currencies.",
          "description": "Returns a list of all currencies.",
          "operationId": "FinanceTypesCurrenciesGet"
        }
      },
      "/finance/v1/types/payment-methods": {
        "get": {
          "tags": [
            "Types"
          ],
          "summary": "Returns a list of all supported payment methods.",
          "description": "Returns a list of all supported payment methods.",
          "operationId": "FinanceTypesPayment-methodsGet"
        }
      },
      "/finance/v1/types/service-types": {
        "get": {
          "tags": [
            "Types"
          ],
          "summary": "Returns a list of all supported service types.",
          "description": "Returns a list of all supported service types.",
          "operationId": "FinanceTypesService-typesGet"
        }
      },
      "/finance/v1/types/vat": {
        "get": {
          "tags": [
            "Types"
          ],
          "summary": "Returns a list of all VAT types.",
          "description": "Returns a list of all VAT types and percents for a country. Supported:<br />\r\n- Belgium (BE)<br />\r\n- Botswana (BW)<br />\r\n- Cape Verde (CV)<br />\r\n- Croatia (HR)<br />\r\n- Czech Republic (CZ)<br />\r\n- Denmark (DK)<br />\r\n- Finland (FI)<br />\r\n- France (FR) - without the super-reduced 2.1% VAT<br />\r\n- French Polynesia (PF)<br />\r\n- Germany (DE)<br />\r\n- Morocco (MA)<br />\r\n- Netherlands (NL)<br />\r\n- Norway (NO) - without the VAT for raw fish s[...]",
          "operationId": "FinanceTypesVatGet"
        }
      },
      "/settings/v1/capture-policies": {
        "get": {
          "tags": [
            "CapturePolicies"
          ],
          "summary": "Get all capture policies.",
          "description": "Get the list of capture policies.<br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "SettingsCapture-policiesGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/settings/v1/capture-policies/{id}": {
        "get": {
          "tags": [
            "CapturePolicies"
          ],
          "summary": "Get a specific capture policy.",
          "description": "Get a specific capture policy.<br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "SettingsCapture-policiesByIdGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "CapturePolicies"
          ],
          "summary": "Allows to modify properties of a capture policy.",
          "description": "Here is the list of operations that are currently allowed:\r\n- Replace captureNoShowFee flag\r\n- Replace captureCancellationFee flag\r\n- Replace capturePrepayment flag\r\n- Replace PostOtaBankTransferOnCheckOut flag\r\n- Replace capturePayment configuration<br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "SettingsCapture-policiesByIdPatch",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/settings/v1/city-tax": {
        "post": {
          "tags": [
            "CityTax"
          ],
          "summary": "Create a city tax.",
          "description": "You can only create one city tax per property. It can be changed and deleted any time.<br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "SettingsCity-taxPost",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "CityTax"
          ],
          "summary": "Get all city taxes.",
          "description": "Get the list of all city taxes.<br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "SettingsCity-taxGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/settings/v1/city-tax/{id}": {
        "get": {
          "tags": [
            "CityTax"
          ],
          "summary": "Get a specific city tax.",
          "description": "Get a specific city tax.<br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "SettingsCity-taxByIdGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "CityTax"
          ],
          "summary": "Allows to modify city tax",
          "description": "Here is the list of operations that are currently allowed:\r\n- Replace name and description\r\n- Replace value and type\r\n- Replace or delete the VAT type<br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "SettingsCity-taxByIdPatch",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "CityTax"
          ],
          "summary": "Delete a city tax",
          "description": "Use this call to delete a city tax.<br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "SettingsCity-taxByIdDelete",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/settings/v1/sub-accounts": {
        "get": {
          "tags": [
            "CustomSubAccounts"
          ],
          "summary": "Returns a list of all sub-accounts.",
          "description": "Returns a list of all sub-accounts.<br>You must have at least one of these scopes: 'subledger.read, setup.read, setup.manage'.",
          "operationId": "SettingsSub-accountsGet",
          "security": [
            {
              "oauth2": [
                "subledger.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "post": {
          "tags": [
            "CustomSubAccounts"
          ],
          "summary": "Create a sub-account.",
          "description": "Create a sub-account.<br>You must have at least one of these scopes: 'subledger.manage, setup.manage'.",
          "operationId": "SettingsSub-accountsPost",
          "security": [
            {
              "oauth2": [
                "subledger.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/settings/v1/sub-accounts/$count": {
        "get": {
          "tags": [
            "CustomSubAccounts"
          ],
          "summary": "Returns number of sub-accounts.",
          "description": "Returns number of sub-account.<br>You must have at least one of these scopes: 'subledger.read, setup.read, setup.manage'.",
          "operationId": "SettingsSub-accounts$countGet",
          "security": [
            {
              "oauth2": [
                "subledger.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/settings/v1/sub-accounts/{id}": {
        "get": {
          "tags": [
            "CustomSubAccounts"
          ],
          "summary": "Returns one sub-account.",
          "description": "Get a sub-account by ID.<br>You must have at least one of these scopes: 'subledger.read, setup.read, setup.manage'.",
          "operationId": "SettingsSub-accountsByIdGet",
          "security": [
            {
              "oauth2": [
                "subledger.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "CustomSubAccounts"
          ],
          "summary": "Allows to modify the name of the sub-account.",
          "description": "Allows to modify the name of the sub-account.<br>You must have at least one of these scopes: 'subledger.manage, setup.manage'.",
          "operationId": "SettingsSub-accountsByIdPatch",
          "security": [
            {
              "oauth2": [
                "subledger.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "head": {
          "tags": [
            "CustomSubAccounts"
          ],
          "summary": "Check if the sub-account exists.",
          "description": "Check if the sub-account exists.<br>You must have at least one of these scopes: 'subledger.read, setup.read, setup.manage'.",
          "operationId": "SettingsSub-accountsByIdHead",
          "security": [
            {
              "oauth2": [
                "subledger.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "CustomSubAccounts"
          ],
          "summary": "Delete a custom sub-account",
          "description": "Use this call to delete a custom sub-accounts.\r\nWhen you delete a custom sub-account, the corresponding accounting accounts are either archived (if there are some transactions posted),\r\nor deleted (if no transactions were posted).<br>You must have at least one of these scopes: 'subledger.manage, setup.manage'.",
          "operationId": "SettingsSub-accountsByIdDelete",
          "security": [
            {
              "oauth2": [
                "subledger.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/settings/v1/features/{propertyId}": {
        "get": {
          "tags": [
            "FeatureSettings"
          ],
          "summary": "Get feature settings for a property.",
          "description": "Get feature settings for a property.<br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "SettingsFeaturesByPropertyIdGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "FeatureSettings"
          ],
          "summary": "Allows to modify feature settings",
          "description": "Here is the list of operations that are currently allowed:\r\n- Replace areCustomRevenueSubAccountsEnabled flag\r\n- Replace performAccountingWhenInvoiceIsMarkedAsPaid flag\r\n- Replace showRecipientForEachLineItemOnTheInvoice flag\r\n- Replace addCityTaxOnReservationCreation flag\r\n- Replace maxAmountForMinimalInvoices value\r\n- Replace invoiceNumberPattern value\r\n- Replace advanceInvoiceNumberPattern value<br>You must have at least one of these scopes: 'features.t[...]",
          "operationId": "SettingsFeaturesByPropertyIdPatch",
          "security": [
            {
              "oauth2": [
                "features.toggle",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/settings/v1/invoice-address": {
        "get": {
          "tags": [
            "InvoiceAddress"
          ],
          "summary": "Get invoice addresses",
          "description": "Get the list of all invoice addresses.<br>You must have at least one of these scopes: 'setup.read, setup.manage, settings.read, settings.manage'.",
          "operationId": "SettingsInvoice-addressGet",
          "security": [
            {
              "oauth2": [
                "admin",
                "setup.read",
                "setup.manage",
                "settings.read",
                "settings.manage"
              ]
            }
          ]
        },
        "put": {
          "tags": [
            "InvoiceAddress"
          ],
          "summary": "Create or update invoice addresses for one or more properties.",
          "description": "If the address does not exist for one of the specified properties, it is created. If it exists, it is completely replaced.<br>You must have at least one of these scopes: 'setup.manage, settings.manage'.",
          "operationId": "SettingsInvoice-addressPut",
          "security": [
            {
              "oauth2": [
                "admin",
                "setup.manage",
                "settings.manage"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "InvoiceAddress"
          ],
          "summary": "Change fields in the invoice address of one or more properties.",
          "description": "Here is the list of operations that are currently allowed:\r\n- Replace AddressLine1\r\n- Add, replace or delete AddressLine2\r\n- Replace PostalCode\r\n- Replace City\r\n- Replace CountryCode<br>You must have at least one of these scopes: 'setup.manage, settings.manage'.",
          "operationId": "SettingsInvoice-addressPatch",
          "security": [
            {
              "oauth2": [
                "admin",
                "setup.manage",
                "settings.manage"
              ]
            }
          ]
        }
      },
      "/settings/v1/languages": {
        "get": {
          "tags": [
            "Languages"
          ],
          "summary": "Get the language settings for the account",
          "description": "Get the language settings<br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "SettingsLanguagesGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "put": {
          "tags": [
            "Languages"
          ],
          "summary": "Replaces the language settings for the account",
          "description": "Use this call to modify the language settings of the account.<br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "SettingsLanguagesPut",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/settings/v1/properties/{id}": {
        "get": {
          "tags": [
            "PropertySettings"
          ],
          "summary": "Get property settings",
          "description": "Get base settings for a property.<br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "SettingsPropertiesByIdGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/settings/v1/properties/{propertyId}/time-slice-definitions/{id}": {
        "get": {
          "tags": [
            "TimeSliceDefinitions"
          ],
          "summary": "Get a specific time slice definition",
          "description": "Get a specific time slice definition for a property. A time slice definition specifies\r\nthe pattern for recurring time slots. The time slots define when reservations\r\nin the property can start or end.\r\nIt is used in the rate plans when managing prices for renting out the units.<br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "SettingsPropertiesByPropertyIdTime-slice-definitionsByIdGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "TimeSliceDefinitions"
          ],
          "summary": "Modifies a specific time slice definition for the property",
          "description": "Use this call to modify a time slice definition of the property.\r\nHere is the list of operations that are currently allowed:\r\n- Replace Name\r\n- Replace CheckInTime (only possible if the time slice definition is not in-use)\r\n- Replace CheckOutTime (only possible if the time slice definition is not in-use)<br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "SettingsPropertiesByPropertyIdTime-slice-definitionsByIdPatch",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "TimeSliceDefinitions"
          ],
          "summary": "Delete a certain time slice definition",
          "description": "Use this call to delete a time slice definition. This is only possible if a time slice definition is not in-use<br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "SettingsPropertiesByPropertyIdTime-slice-definitionsByIdDelete",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/settings/v1/properties/{propertyId}/time-slice-definitions": {
        "get": {
          "tags": [
            "TimeSliceDefinitions"
          ],
          "summary": "Get time slice definitions",
          "description": "Get all time slice definitions for a property. A time slice definition specifies\r\nthe pattern for recurring time slots. The time slots define when reservations\r\nin the property can start or end.\r\nThey are used in the rate plans when managing prices for renting out the units.<br>You must have at least one of these scopes: 'settings.read, setup.read, setup.manage'.",
          "operationId": "SettingsPropertiesByPropertyIdTime-slice-definitionsGet",
          "security": [
            {
              "oauth2": [
                "settings.read",
                "setup.read",
                "setup.manage",
                "admin"
              ]
            }
          ]
        },
        "post": {
          "tags": [
            "TimeSliceDefinitions"
          ],
          "summary": "Creates a time slice definition",
          "description": "Use this call to create a time slice definition.<br>You must have at least one of these scopes: 'settings.manage, setup.manage'.",
          "operationId": "SettingsPropertiesByPropertyIdTime-slice-definitionsPost",
          "security": [
            {
              "oauth2": [
                "settings.manage",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/account/v1/accounts/current": {
        "get": {
          "tags": [
            "Account"
          ],
          "summary": "Returns the current account.",
          "description": "Retrieves information about the current account.<br>You need to be authorized (no particular scope required)",
          "operationId": "AccountAccountsCurrentGet",
          "security": [
            {
              "oauth2": [ ]
            }
          ]
        },
        "put": {
          "tags": [
            "Account"
          ],
          "summary": "Replaces an existing account.",
          "description": "Completely replaces an account with the new definition passed in. The old data will be lost.<br>You must have this scope: 'account.manage'.",
          "operationId": "AccountAccountsCurrentPut",
          "security": [
            {
              "oauth2": [
                "account.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/account/v1/accounts": {
        "get": {
          "tags": [
            "Account"
          ],
          "summary": "Returns all accounts",
          "description": "Get the list of accounts.<br>You must have this scope: 'accounts.read'.",
          "operationId": "AccountAccountsGet",
          "security": [
            {
              "oauth2": [
                "accounts.read"
              ]
            }
          ]
        },
        "post": {
          "tags": [
            "Account"
          ],
          "summary": "Creates an account with an admin user.",
          "description": "Use this call to create a new account.<br>You must have this scope: 'account.create'.",
          "operationId": "AccountAccountsPost",
          "security": [
            {
              "oauth2": [
                "account.create"
              ]
            }
          ]
        }
      },
      "/account/v1/account-actions/current/suspend": {
        "put": {
          "tags": [
            "AccountActions"
          ],
          "summary": "Suspend the account.",
          "description": "Suspends the current account.\r\nThis changes the account type to 'Suspended'.<br>You must have this scope: 'account.manage'.",
          "operationId": "AccountAccount-actionsCurrentSuspendPut",
          "security": [
            {
              "oauth2": [
                "account.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/account/v1/account-actions/current/set-live": {
        "put": {
          "tags": [
            "AccountActions"
          ],
          "summary": "Move the account to live.",
          "description": "Move the current account to live.\r\nThis changes the account type to 'Live'.<br>You must have this scope: 'account.manage'.",
          "operationId": "AccountAccount-actionsCurrentSet-livePut",
          "security": [
            {
              "oauth2": [
                "account.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/operations/v1/maintenances": {
        "get": {
          "tags": [
            "Maintenance"
          ],
          "summary": "Get list of maintenances",
          "description": "Get a list of maintenances matching your filter.<br>You must have at least one of these scopes: 'maintenances.read, maintenances.manage'.",
          "operationId": "OperationsMaintenancesGet",
          "security": [
            {
              "oauth2": [
                "maintenances.read",
                "maintenances.manage",
                "admin"
              ]
            }
          ]
        },
        "post": {
          "tags": [
            "Maintenance"
          ],
          "summary": "Create a new maintenance window",
          "description": "Use this call to create a new maintenance window for the given unit. You can only create maintenances for today and days in the future.<br>You must have at least one of these scopes: 'maintenances.create, maintenances.manage'.",
          "operationId": "OperationsMaintenancesPost",
          "security": [
            {
              "oauth2": [
                "maintenances.create",
                "maintenances.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/operations/v1/maintenances/$count": {
        "get": {
          "tags": [
            "Maintenance"
          ],
          "summary": "Returns number of maintenances",
          "description": "Returns the number of maintenances matching your filter.<br>You must have at least one of these scopes: 'maintenances.read, maintenances.manage'.",
          "operationId": "OperationsMaintenances$countGet",
          "security": [
            {
              "oauth2": [
                "maintenances.read",
                "maintenances.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/operations/v1/maintenances/bulk": {
        "post": {
          "tags": [
            "Maintenance"
          ],
          "summary": "Create multiple maintenances",
          "description": "Use this call to create multiple maintenances.<br>You must have at least one of these scopes: 'maintenances.create, setup.manage'.",
          "operationId": "OperationsMaintenancesBulkPost",
          "security": [
            {
              "oauth2": [
                "maintenances.create",
                "setup.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/operations/v1/maintenances/{id}": {
        "patch": {
          "tags": [
            "Maintenance"
          ],
          "summary": "Modify a maintenance",
          "description": "You can only change maintenances which are in the future or still ongoing today.\r\nHere is the list of operations that are currently allowed:\r\n- Add, replace and remove Description\r\n- Replace From and To. 'From' cannot be changed, if the maintenance started yesterday or before.<br>You must have this scope: 'maintenances.manage'.",
          "operationId": "OperationsMaintenancesByIdPatch",
          "security": [
            {
              "oauth2": [
                "maintenances.manage",
                "admin"
              ]
            }
          ]
        },
        "delete": {
          "tags": [
            "Maintenance"
          ],
          "summary": "Delete a maintenance",
          "description": "Use this call to delete a maintenance. It is not possible to delete maintenances that started yesterday or earlier.<br>You must have at least one of these scopes: 'maintenances.delete, maintenances.manage'.",
          "operationId": "OperationsMaintenancesByIdDelete",
          "security": [
            {
              "oauth2": [
                "maintenances.delete",
                "maintenances.manage",
                "admin"
              ]
            }
          ]
        },
        "get": {
          "tags": [
            "Maintenance"
          ],
          "summary": "Get a specific maintenance",
          "description": "Get a specific maintenance by ID.<br>You must have at least one of these scopes: 'maintenances.read, maintenances.manage'.",
          "operationId": "OperationsMaintenancesByIdGet",
          "security": [
            {
              "oauth2": [
                "maintenances.read",
                "maintenances.manage",
                "admin"
              ]
            }
          ]
        },
        "head": {
          "tags": [
            "Maintenance"
          ],
          "summary": "Check if a maintenance exists",
          "description": "Check if a maintenance exists by ID.<br>You must have at least one of these scopes: 'maintenances.read, maintenances.manage'.",
          "operationId": "OperationsMaintenancesByIdHead",
          "security": [
            {
              "oauth2": [
                "maintenances.read",
                "maintenances.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/operations/v1/night-audit": {
        "put": {
          "tags": [
            "Operations"
          ],
          "summary": "Performs the night audit for one property.",
          "description": "The night audit will post all charges for services that were delivered on the past business day in the folio and set all occupied rooms to 'Dirty'<br>You must have at least one of these scopes: 'operations.manage, operations.trigger-night-audit'.",
          "operationId": "OperationsNight-auditPut",
          "security": [
            {
              "oauth2": [
                "operations.manage",
                "operations.trigger-night-audit",
                "admin"
              ]
            }
          ]
        }
      },
      "/operations/v1/units-condition": {
        "put": {
          "tags": [
            "Operations"
          ],
          "summary": "Change the condition of a unit",
          "description": "<br>You must have this scope: 'operations.change-room-state'.",
          "operationId": "OperationsUnits-conditionPut",
          "security": [
            {
              "oauth2": [
                "operations.change-room-state",
                "admin"
              ]
            }
          ]
        }
      },
      "/logs/v1/booking/reservation": {
        "get": {
          "tags": [
            "BookingLogs"
          ],
          "summary": "Returns reservation change log entries sorted by the timestamp.",
          "description": "<br>You must have this scope: 'logs.read'.",
          "operationId": "LogsBookingReservationGet",
          "security": [
            {
              "oauth2": [
                "logs.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/logs/v1/finance/folio": {
        "get": {
          "tags": [
            "FinanceLogs"
          ],
          "summary": "Returns folio change log entries sorted by the timestamp.",
          "description": "<br>You must have this scope: 'logs.read'.",
          "operationId": "LogsFinanceFolioGet",
          "security": [
            {
              "oauth2": [
                "logs.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/logs/v1/finance/night-audit": {
        "get": {
          "tags": [
            "FinanceLogs"
          ],
          "summary": "Returns the night audit logs.",
          "description": "Returns a log of all night audits\r\nNewest log entries are returned first.<br>You must have this scope: 'logs.read'.",
          "operationId": "LogsFinanceNight-auditGet",
          "security": [
            {
              "oauth2": [
                "logs.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/logs/v1/finance/transactions-export": {
        "get": {
          "tags": [
            "FinanceLogs"
          ],
          "summary": "Returns the audit log for all accounting exports that have been done.",
          "description": "Returns the audit log for all exports if accounting data that have been done.<br>You must have this scope: 'logs.read'.",
          "operationId": "LogsFinanceTransactions-exportGet",
          "security": [
            {
              "oauth2": [
                "logs.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/reports/v1/reports/ordered-services": {
        "get": {
          "tags": [
            "Reports"
          ],
          "summary": "List of ordered services",
          "description": "Returns a list of ordered services per day with information about the guest and the reservation this service was ordered for.<br>You must have this scope: 'reports.read'.",
          "operationId": "ReportsReportsOrdered-servicesGet",
          "security": [
            {
              "oauth2": [
                "reports.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/reports/v1/reports/arrivals": {
        "get": {
          "tags": [
            "Reports"
          ],
          "summary": "Returns the number of arrivals in a month for a property",
          "description": "Returns number of arriving guests for a property for a certain month. Only over-night rateplans are considered.<br />\r\nIncludes statistical information on purpose of travel, and nationality. The data is taken from the primary guest only.\r\nThe status considered are: in-house, confirmed, and checked out.<br>You must have this scope: 'reports.read'.",
          "operationId": "ReportsReportsArrivalsGet",
          "security": [
            {
              "oauth2": [
                "reports.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/reports/v1/reports/property-performance": {
        "get": {
          "tags": [
            "Reports"
          ],
          "summary": "Returns the property performance report which includes the ADR and the RevPAR for each business day.",
          "description": "The property performance API return you key performance indicator for the selected property like occupancy, ADR and RevPAR.\r\nIt only considers the originally booked amounts for sold units excluding any additional services or manually posted charges\r\nor allowances. The results can be filterd to only show you data for a certain part of the business. For example you can exclude\r\nday-use reservations or complimentary rate plans.<br>You must have this scope: 'reports.r[...]",
          "operationId": "ReportsReportsProperty-performanceGet",
          "security": [
            {
              "oauth2": [
                "reports.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/reports/v1/reports/company-invoices-vat": {
        "get": {
          "tags": [
            "Reports"
          ],
          "summary": "Returns the list of company invoices with information on the company and the VAT breakdown",
          "description": "<br>You must have this scope: 'reports.read'.",
          "operationId": "ReportsReportsCompany-invoices-vatGet",
          "security": [
            {
              "oauth2": [
                "reports.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/reports/v1/reports/revenues": {
        "get": {
          "tags": [
            "Reports"
          ],
          "summary": "Returns the revenues report for a property",
          "description": "<br>You must have this scope: 'reports.read'.",
          "operationId": "ReportsReportsRevenuesGet",
          "security": [
            {
              "oauth2": [
                "reports.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/availability/v1/units": {
        "get": {
          "tags": [
            "Availability"
          ],
          "summary": "Get a list of all available units in a property",
          "description": "Get the list of available units for a specific property and time period.<br>You must have this scope: 'availability.read'.",
          "operationId": "AvailabilityUnitsGet",
          "security": [
            {
              "oauth2": [
                "availability.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/availability/v1/unit-groups": {
        "get": {
          "tags": [
            "Availability"
          ],
          "summary": "Get a list of all available unit groups in a property",
          "description": "Get the list of available unit groups for a specific property and time period.<br>You must have this scope: 'availability.read'.",
          "operationId": "AvailabilityUnit-groupsGet",
          "security": [
            {
              "oauth2": [
                "availability.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/availability/v1/unit-groups/{id}": {
        "patch": {
          "tags": [
            "Availability"
          ],
          "summary": "Allows to modify the unit group availability",
          "description": "You can replace AllowedOverbooking for a unit group<br>You must have this scope: 'availability.manage'.",
          "operationId": "AvailabilityUnit-groupsByIdPatch",
          "security": [
            {
              "oauth2": [
                "availability.manage",
                "admin"
              ]
            }
          ]
        }
      },
      "/availability/v1/services": {
        "get": {
          "tags": [
            "Availability"
          ],
          "summary": "Get a list of all available services in a property",
          "description": "Get the list of available services for a specific property and time period.<br>You must have this scope: 'availability.read'.",
          "operationId": "AvailabilityServicesGet",
          "security": [
            {
              "oauth2": [
                "availability.read",
                "admin"
              ]
            }
          ]
        }
      },
      "/availability/v1/reservations/{id}/units": {
        "get": {
          "tags": [
            "ReservationAvailability"
          ],
          "summary": "Get a list of all available units for a reservation",
          "description": "Get the list of available units for a specific reservation and time period.<br>You must have at least one of these scopes: 'availability.read, reservations.manage'.",
          "operationId": "AvailabilityReservationsByIdUnitsGet",
          "security": [
            {
              "oauth2": [
                "availability.read",
                "reservations.manage",
                "admin"
              ]
            }
          ]
        }
      }
    },
    "securityDefinitions": {
      "oauth2": {
        "type": "oauth2",
        "flow": "implicit",
        "authorizationUrl": "https://identity.apaleo.com/connect/authorize",
        "scopes": {
          "admin": "Full access",
          "reservations.import": "Import reservations"
        }
      }
    }
  }